In [1]:
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PointStruct
from typing import Hashable, Any

import pandas as pd
import openai  

import os
import cohere

co_client = cohere.Client()

### Read the sampled dataset woth amazon inventory data

In [2]:
df_items = pd.read_json('../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl', lines=True)

In [3]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,All Electronics,Syncwire Bluetooth 5.3 FM Transmitter Car Adap...,4.6,188,[[𝙃𝙪𝙢𝙖𝙣𝙞𝙯𝙚𝙙 𝘼𝙢𝙗𝙞𝙚𝙣𝙩 𝙇𝙞𝙜𝙝𝙩 𝙎𝙬𝙞𝙩𝙘𝙝 𝘿𝙚𝙨𝙞𝙜𝙣] Doubl...,[],24.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Syncwire Bluetooth 5.3 FM Transmit...,Syncwire,"[Electronics, Portable Audio & Video, MP3 & MP...",{'Package Dimensions': '3.46 x 2.36 x 1.65 inc...,B0BTP3PQ6Y,NaN
1,Cell Phones & Accessories,Google Pixel 7 Pro - 5G Android Phone - Unlock...,4.2,1385,[Google Pixel 7 Pro is Google’s best-of-everyt...,"[Meet Pixel 7 Pro, Google’s best-of-everything...",1099.00,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Best camera feature on Google Pixe...,Google,"[Electronics, New Arrivals - Electronics]",{'Product Dimensions': '6.42 x 3.02 x 0.34 inc...,B0BVX6BBMJ,NaN
2,Cell Phones & Accessories,Shangpule Compatible with Fitbit Charge 5 Band...,3.8,315,[Compatible with Fitbit Charge 5 Fitness Activ...,[],16.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Would not stay attached', 'url': '...",NaN,"[Electronics, Wearable Technology, Arm & Wrist...","{'Date First Available': 'October 14, 2022'}",B0BJ6PY8Z6,NaN
3,All Electronics,NexFoto Digital Picture Frame with Remote Cont...,4.3,114,[Every Moment Counts: Sharing life moments wit...,[],59.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Every Moment Counts.', 'url': 'htt...",NexFoto,"[Electronics, Camera & Photo, Lighting & Studi...",{'Product Dimensions': '8.7 x 6.14 x 0.98 inch...,B0C2TSD8FK,NaN
4,All Electronics,"ivoler Laptop Stand, Laptop Holder Riser Compu...",4.7,6783,[COMPATIBILITY: The laptop & tablet stand supp...,[],15.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'laptop stand with must have featur...,ivoler,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '9.4 x 1.73 x 1 inches'...,B0B63VL3N6,NaN

In [4]:
list[tuple[Hashable, Any]](df_items["features"].items())[1] ## feature 0 is null

(1,
 ['Google Pixel 7 Pro is Google’s best-of-everything phone; powered by Google Tensor G2, it’s faster, more efficient, and more secure, with the best photo and video quality yet on Pixel[1].Other camera description:Front,Rear',
  'Unlocked Android 5G phone gives you the flexibility to change carriers and choose your own data plan[2]; works with Google Fi, Verizon, T-Mobile, AT&T, and other major carriers',
  'Pixel’s Adaptive Battery can last over 24 hours; when Extreme Battery Saver is turned on, it can last up to 72 hours[3]',
  'The Google Pixel 7 Pro 6.7-inch Smooth Display makes everything stunning and immersive[4]; it intelligently adjusts up to 120Hz for smoother, more responsive performance[4]',
  'Google Pixel 7 Pro has a 5x telephoto lens with 30x Super Res Zoom[5]; the upgraded ultrawide lens powers Macro Focus to capture the smallest details',
  'With Google Tensor G2 and the Titan M2 security chip, your Pixel is built with multiple layers of security to help keep your personal info safe',
  'VPN by Google One (coming soon) is built into Pixel 7 Pro to help protect your online activity, no matter what app or web browser you use[6]',
  'Get hands-free help with Google Assistant, pair devices easily, and use Find My Device to locate your Pixel phone, Google Pixel Watch, or Pixel Buds[7]',
  'With its durable design and IP68 protection, your phone can handle water and dust[8]; it’s also scratch-resistant, with Corning[R] Gorilla[R] Glass Victus[TM]',
  'Please refer to the product description section below for all applicable legal disclaimers denoted by the bracketed numbers in the preceding bullet points (e.g., [1], [2], etc.)'])

In [5]:
list[tuple[Hashable, Any]](df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/41nIhnMtDIL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41nIhnMtDIL._AC_.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/71-AHxfs0BL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51W+VnyLGaL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51W+VnyLGaL._AC_.jpg',
   'variant': 'PT01',
   'hi_res': 'https://m.media-amazon.com/images/I/811qrQPq0lL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51y374XGX4L._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51y374XGX4L._AC_.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/71gDXqGU1NL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51EUA-oQ-NL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51EUA-oQ-NL._AC_.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/71RqqWz0l7L._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51Zu-2NzW1L._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51Zu-2NzW1L._AC_.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/71elAGVJUJL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51Wse0WAGaL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51Wse0WAGaL._AC_.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/71RcI46fpxL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51DK0X0waQL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51DK0X0waQL._AC_.jpg',
   'variant': 'PT06',
   'hi_res': 'https://m.media-amazon.com/images/I/715ZYUrubcL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51R3UJGCrRL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51R3UJGCrRL._AC_.jpg',
   'variant': 'PT07',
   'hi_res': 'https://m.media-amazon.com/images/I/7124qtQkuXL._AC_SL1500_.jpg'}])

## Preprocess title and feature

In [6]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [7]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [8]:
df_items["description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [9]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,image
0,All Electronics,Syncwire Bluetooth 5.3 FM Transmitter Car Adap...,4.6,188,[[𝙃𝙪𝙢𝙖𝙣𝙞𝙯𝙚𝙙 𝘼𝙢𝙗𝙞𝙚𝙣𝙩 𝙇𝙞𝙜𝙝𝙩 𝙎𝙬𝙞𝙩𝙘𝙝 𝘿𝙚𝙨𝙞𝙜𝙣] Doubl...,Syncwire Bluetooth 5.3 FM Transmitter Car Adap...,24.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Syncwire Bluetooth 5.3 FM Transmit...,Syncwire,"[Electronics, Portable Audio & Video, MP3 & MP...",{'Package Dimensions': '3.46 x 2.36 x 1.65 inc...,B0BTP3PQ6Y,NaN,https://m.media-amazon.com/images/I/41nIhnMtDI...
1,Cell Phones & Accessories,Google Pixel 7 Pro - 5G Android Phone - Unlock...,4.2,1385,[Google Pixel 7 Pro is Google’s best-of-everyt...,Google Pixel 7 Pro - 5G Android Phone - Unlock...,1099.00,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Best camera feature on Google Pixe...,Google,"[Electronics, New Arrivals - Electronics]",{'Product Dimensions': '6.42 x 3.02 x 0.34 inc...,B0BVX6BBMJ,NaN,https://m.media-amazon.com/images/I/4161bAE+CA...
2,Cell Phones & Accessories,Shangpule Compatible with Fitbit Charge 5 Band...,3.8,315,[Compatible with Fitbit Charge 5 Fitness Activ...,Shangpule Compatible with Fitbit Charge 5 Band...,16.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Would not stay attached', 'url': '...",NaN,"[Electronics, Wearable Technology, Arm & Wrist...","{'Date First Available': 'October 14, 2022'}",B0BJ6PY8Z6,NaN,https://m.media-amazon.com/images/I/413TlX98O-...
3,All Electronics,NexFoto Digital Picture Frame with Remote Cont...,4.3,114,[Every Moment Counts: Sharing life moments wit...,NexFoto Digital Picture Frame with Remote Cont...,59.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Every Moment Counts.', 'url': 'htt...",NexFoto,"[Electronics, Camera & Photo, Lighting & Studi...",{'Product Dimensions': '8.7 x 6.14 x 0.98 inch...,B0C2TSD8FK,NaN,https://m.media-amazon.com/images/I/4153deE+9c...
4,All Electronics,"ivoler Laptop Stand, Laptop Holder Riser Compu...",4.7,6783,[COMPATIBILITY: The laptop & tablet stand supp...,"ivoler Laptop Stand, Laptop Holder Riser Compu...",15.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'laptop stand with must have featur...,ivoler,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '9.4 x 1.73 x 1 inches'...,B0B63VL3N6,NaN,https://m.media-amazon.com/images/I/41WRzASGgj...

### Look the "title" and "features" it have the same description so we use .join() to combine it with each other on one string line on index 0

In [10]:
list[tuple[Hashable, Any]](df_items["description"].items())[0]

(0,
 'Syncwire Bluetooth 5.3 FM Transmitter Car Adapter 48W (PD 36W & 12W) [Light Switch] [HiFi Bass Sound] [Fast Charging] Wireless Radio Music Adapter LED Display Hands-Free Calling Support USB Drive [𝙃𝙪𝙢𝙖𝙣𝙞𝙯𝙚𝙙 𝘼𝙢𝙗𝙞𝙚𝙣𝙩 𝙇𝙞𝙜𝙝𝙩 𝙎𝙬𝙞𝙩𝙘𝙝 𝘿𝙚𝙨𝙞𝙜𝙣] Double press the red "B" button to turn off/on the colored lights directly. [𝙐𝙥𝙜𝙧𝙖𝙙𝙚𝙙 𝘽𝙡𝙪𝙚𝙩𝙤𝙤𝙩𝙝 𝟱.𝟯 𝙏𝙚𝙘𝙝𝙣𝙤𝙡𝙤𝙜𝙮] The latest Bluetooth 5.3 technology, optimizing the transmission delay and connection defect problems, Bluetooth 5.3 will bring you a faster, more stable and smarter connection with less sound quality loss,uninterrupted calls and music experience. It takes only 1 second to complete pairing, and no need to repeat pairing after the first successful pairing with your device. [𝙄𝙣𝙩𝙚𝙡𝙡𝙞𝙜𝙚𝙣𝙩 𝘿𝙪𝙖𝙡 𝙐𝙎𝘽 𝙋𝙤𝙧𝙩𝙨 & 𝙁𝙖𝙨𝙩 𝘾𝙝𝙖𝙧𝙜𝙞𝙣𝙜] Coming with 2 USB ports(PD 36W and USB A 12W), can charge two devices simultaneously. Built-in over-current protection, over-voltage protection, intelligent temperature control, short circuit protection, it will effectively ensure safe charging. [𝙂𝙧𝙚𝙖𝙩 𝘾𝙡𝙚𝙖𝙧 𝙈𝙪𝙨𝙞𝙘 𝙎𝙩𝙧𝙚𝙖𝙢𝙞𝙣𝙜] Bluetooth 5.3 provides a stable connection, while Noise Suppression (CVC) technology and echo-cancellation grants an amazing hands-free calling experience. In addition, this Bluetooth car adapter supports bluetooth connection and USB stick connection (≤64GB). [𝙃𝙞-𝙁𝙞 𝘿𝙚𝙚𝙥 𝘽𝙖𝙨𝙨 & 𝘽𝙖𝙘𝙠𝙡𝙞𝙩] Just press the button "B" and you will enjoy powerful deep bass and immersive stereo sound. The high-fidelity Hi-Fi sound quality will also make the music more dynamic and pleasing to the ear, taking your passion for music to a new level.')

## Sample 50 items from the dataset

In [11]:
df_sample = df_items.sample(50, random_state=42)

In [12]:
len(df_sample)

50

we prepare 50 sample with these below data feature for embeding

In [13]:
data_to_embed = df_sample[["description", "image", "rating_number", "price", "average_rating", "parent_asin"]]. to_dict(orient="records")

In [14]:
data_to_embed

[{'description': "BoYata Screen Cleaner Kit 4PCS, 3-in-1 Touchscreen Mist Cleaner Spray Bottle Tool & Microfiber Cloth, Portable Reusable Fingerprint-Proof Spray Bottle for Phone/Laptop/Tablet/TV/Monitor/Car Screens Not Containing Cleaning Fluid: BoYata all-in-one detachable fingerprint-proof computer screen cleaner consists of a protective case, microfiber cloth shell and spray bottle (without cleaning fluid), integrated spray and wipe in one. Extremely convenient to use after filling cleaning fluid. Note: please don't put corrosive liquids. Wide Compatibility: The touch screen mist cleaner is useful for screen cleaning. Suitable for all phones/ tablets/ laptops/ monitors/ TVs/ cars screens, glass surface etc. Spray and wipe in one for quick and easy cleaning, making your screen look as good as new. Safe and no damage to your screen. Powerful Cleaning: The updated microfiber cloth of the screen cleaner is easy to move fingerprints, dust, grease, dirt on screen without streaking or scratching. Well absorbent and no shedding hair. Unlike other products, it has a silicone scraper on the back that effectively removes stubborn stains on the screen. Washable & Reusable: The gentle microfiber cloth with a hot pressing technique, not degumming and the laptop screen cleaner is washable that the cleaner surface is dirty, can be washed directly with clean water and then reuse after drying. The 10,5 ml spray bottle can easily be refilled to use again. Lightweight & Portable: The phone screen cleaner is very lightweight in size and weight, a size of a lipstick, fits easily into a pocket, handbag, makeup bag, backpack or car, etc, easy to carry. The ABS transparent protective case effectively protects your bag or pocket from getting dirty. Kindly contact us if there is any product issue.",
  'image': 'https://m.media-amazon.com/images/I/41x2+vIHjNL._AC_.jpg',
  'rating_number': 105,
  'price': 11.99,
  'average_rating': 4.6,
  'parent_asin': 'B0C3VNSX6X'},
 {'description': 'Smart Watch, Fitness Tracker with 5ATM Waterproof, Heart Rate Monitor and Blood Oxygen Monitor, Sleep Monitor 1.69-inch HD Color Screen Smartwatch for Men Women Compatible with iPhone & Android 【Customized Your Unique Smart watch】Boean smart watch with 1.69-inch TFT-LCD full touch screen technology makes your operation quick and easy. You can set the watch face to show your personality with the existing images or upload images. The smart watch will vibrate when receiving incoming calls, message notifications from Facebook, Instagram, Twitter, WhatsApp, etc. Never miss any important calls or messages. 【Long Battery & 5ATM Waterproof】It only takes 2 hours to charge and can be used for 8-15 days or 30 days standby time. Boean Smart Watch is designed with 5ATM waterproof rating (50m waterproof), you can wear it while swimming or sweating out. (Note: the smartwatch does not prevent hot water and sea water). 【24/7 Heart Rate Monitor & Sleep Tracker】Advanced HR sensor for accurate and effective heart rate monitoring, helping you better understand your health and making a reasonable adjustment to your lifestyle. Automatic sleep tracking can monitor your sleep status (deep sleep, shallow sleep, awakening) . (Note: the data cannot be used as a medical-grade test) 【Support 14 Sport Modes】Boean fitness watch supports 14 sport modes records your all-day activities including steps, distance, calories, sleep status and heart rate. It gives you more details into your body activities and helps you exercise scientifically and achieve fitness goals. Connect GPS in your mobile phone to track your exercise process. 【More Practical Tools and Compatibility】 When you connect the smart watch to your smartphone, you can control the music player, view the local weather today, and support the mobile search function. Boean smartwatch is compatible with most IOS 9.0 & Android 6.0 and above smartphones. Go to App Store or Google Play to download and install “VeryFit” for free.',
  'image': 'https://m.media-amazon.com/images/I/41pqyVy2ZrL._AC_.jpg',
  'rating_number': 230,
  'price': 49.99,
  'average_rating': 4.2,
  'parent_asin': 'B0B2R7HK3C'},
 {'description': 'USB C Memory Stick 1TB,Dual USB 3.1 Flash Drive 3 in 1 Type-C Thumb Drive NEHEUI Phone Photo Stick Date Storage Back up Pendrive USB C Stick Drive for Android Phones/PC/MacBook pro and Computer(Pink Dual USB 3.1 & USB C Flash Drive 1TB. Compatible with OTG enabled devices. With USB-C interface and micro USB interface, you can use this USB C flash drive. It is usually used for storage, data backup and computer file transmission, which can meet your daily needs for photo, music, video, file storage and transmission at work, school, home and travel. This Thumb Drive 1000GB Supports Almost All Operating Systems, Including Windows2000/7/8/8.1/10/vista/xp, Compatible with Any Device with a Usb Port/Type A and Type C port. Reliably Store Photos, Videos, Music, and Other Files.Warranty 90 Days, if You Encounter Problems, You Can Replace USB Flash Drives at any time. The Weight of USB C Zip Dirve is Only 0.036Lb,Type C Thumb Drive USB C Casing is Made of Premium Zinc Alloy, which Makes the USB Drive Extremely Sturdy and Durable.360° Rotation Protecting Cap Design Prevent Cap Losing.You to Easily Connect the Usb Drives to A Key Or Lanyard For Easy Portability.(Can be carried on keychains, belts, wallets, school bags, etc.) Phone picture storage drive for smart cell phones with the USB 3.1 and USB Type-C interface,External date storage drive for Computer & Photo Stick for android phones.You Can Easily Transfer Files and Data Between Smartphones, Tablets and Computers instead of Using WiFi and Cloud Services, Efficiently Save File Transfer Time and Greatly Improve Work Efficiency. Phone picture storage drive for smart cell phones with the USB 3.1 and USB Type-C interface,External date storage drive for Computer & Photo Stick for android phones.You Can Easily Transfer Files and Data Between Smartphones, Tablets and Computers instead of Using WiFi and Cloud Services, Efficiently Save File Transfer Time and Greatly Improve Work Efficiency.',
  'image': 'https://m.media-amazon.com/images/I/41iPVRTJZgL._AC_.jpg',
  'rating_number': 264,
  'price': 49.89,
  'average_rating': 3.7,
  'parent_asin': 'B0C4SRVMHP'},
 {'description': 'KOSPET Smart Watches for Men - 5ATM/IP69K Waterproof Fitness Smart Watch for Android iPhones with Heart Rate Blood Pressure - 1.72" Tactical Military Sports Smartwatch ✅Military Standard Verification - Special composite materials and metal shell makes our smart watches for women and men pass dozens of standard tests including temperature, low pressure altitude, dustproof, salt spray, fluid contamination, etc. Fitness watch can undoubtedly become your reliable companion when you like outdoor activities ✅Extremely Resistant to Damage - Our fully enclosed slim shell designed android smart watch can be immersed in 50m (5ATM waterproof) deep water. Our military watch is a proven survivor of extreme conditions and has passed the drilling, crushing and hot steam scouring test which makes sports watch suitable to be used in high temperature and high pressure environments ✅Live an Efficient Life - To make your everyday life easier, Kospet smart watch for android phones comes with a touch screen and features like 1.72” high-end brightness and 280x320 resolutions for a better visual experience. Thanks to 380mAh Li-Polymer battery of heart rate monitor watch that has a standby time above 50days. Communicate and entertain all week long with 15 days use time ✅Keep your Activities on Track - Kospet mens smartwatch comes with 24 sports modes, such as running, walking, trail running, cycling, climbing, skiing, swimming, basketball, football and baseball. Efficiency and accuracy of our bluetooth watch data reminds you to rest timely and perform all your physical activities ✅Know Your Health Status - The blood pressure watch has a real time monitoring feature which collects data about your health, heart-rate for 24 hours and real time blood pressure and blood oxygen. Fitness watches for men and women help you to monitor sleep. Fitness tracker watch contains a pedometer which allows controlling the calories burnt throughout the day',
  'image': 'https://m.media-amazon.com/images/I/41Y1PTG87AL._AC_.jpg',
  'rating_number': 2455,
  'price': 59.99,
  'average_rating': 4.0,
  'parent_asin': 'B0B8S534KB'},
 {'description': "Mini Spy Camera Wireless Hidden Camera Portable Small Camera with Motion Detection and Night Vision Nanny Cam no WiFi Security Camera Pet Camera for Cat/Cop cam No WiFi Need,unlimited distance: all you need is an SD card plugged into your mini camera, and with enough power and memory（Maximum extended memory 128 GB，NO included in the product). You can record about 100 minutes after full charge. Also it can record throughout the day while charging This small camera does motion and loop. You can leave it out 24/7,When memory runs out, the new video file will automatically overwrite the old one. Automatic change in night vision ＆ motion detection.The tiny camera is equipped with 1 super integrated infrared LED which achieves more than 7 LEDs and With this motion detection mode, the spy cam can also detect moving objects when it is still.Even in the dark, you can wake up the next day knowing what your pet or home is doing. Multi-scene practicability：you can attach it to pet'collar with clip, which is suitable for any size collar.Also it upgraded with built-in strong magnet,can be attach it to any magnetically supported material.The mini wireless security spy camera smaller than one square inch.Perfect surveillance cameras for home security.Also It is a good security camera wireless for car, office, shop,monitored family Safety situation and protection of property safety. Easy to use: If you want to get a view of your pet,just insert the SD card into the camera, turn on the camera, attach the nanny cam to the pet's collar through the clip, and turn on the recording function.Then simply upload the nanny cam through USB to your computer to share within seconds, you can observe what your pet sees everywhere he walks by.For example, some of the corners that he goes to you can't see, grass, high buildings. A full set of accessories：Mini camera x1, Swivel clip for body camera wearing x1, Custom-built bracket for mounting x1, Memory card reader x1.collar is not included.",
  'image': 'https://m.media-amazon.com/images/I/41VnGSjoxKL._AC_.jpg',
  'rating_number': 107,
  'price': 26.99,
  'average_rating': 3.1,
  'parent_asin': 'B0BDZ5V6BY'},
 {'description': 'Westinghouse 27" Full HD 1080p LED IPS Home Office Computer Monitor, Flicker-Free 75Hz Monitor 27 Inch with IPS Display, Blue Light Filter, and Warm & Cool Mode Viewing, HDMI & VGA Compatible Full High-Definition Display - Get crisp, clear images with this full HD 1080p monitor! Our 27 inch monitor has double the image resolution of standard monitors. The IPS panel delivers top color accuracy and sharp visibility, elevating your overall visual experience no matter your vantage point! Innovative EyeRest Technology - Our LED monitor is designed to relieve your eyes from long periods of computer screen exposure. Developed with EyeRest Technology, it reduces digital eye strain and fatigue with its flicker-free, anti-glare, low blue light settings and warm & cool mode viewing. Thin Bezel Design - This 27in monitor is functional and stylish - enhancing your workspace and providing you with a seamless multi-monitor viewing experience. Our computer display has a 16:9 aspect ratio for a wider viewing angle, optimal edge-to-edge screen visibility, and reduced reflection. Adjustable Tilt Screen - Our office monitor offers enhanced viewing comfort with its flexible tilt screen. Simply adjust the angle of your flat monitor forward or backward to your preferred position. HDMI and VGA Compatible - Effortlessly link your devices with the connectivity features of our desktop monitor. This VGA and HDMI monitor is compatible with full high definition and traditional PC use. It has ports both for old and newer electronics, displaying smooth visuals no matter your device.',
  'image': 'https://m.media-amazon.com/images/I/41PTVisFURL._AC_.jpg',
  'rating_number': 106,
  'price': 119.0,
  'average_rating': 4.2,
  'parent_asin': 'B0B2D6Z7P9'},
 {'description': 'Camera Tripod, 80/84 inches Heavy Duty Tripod for Camera and Phone, 82" Camera Monopod Tripod, DSLR Binoculars Spotting Scope Camcorders Video Tripod Stand, 360 Degree Ball Head, 35 lbs Loads 【360° Panoramic Shooting】The camera tripod has an independent pan lock that enables you to rotate the head 360° panning, and a ball lock to position a camera at +90°/ -70° tilt with the cut-notch located on the side of the head, satisfying all the needs of vertical, horizontal, and overhead photography, etc. 1/4" quick release plate mount can quick connection to all DSLR cameras, phones, camcorders, binoculars, spotting scope, projector, telescope, laser level and digital cameras. 【 Aluminum Camera Tripod 】 38mm diameters Larger ball head is aluminum alloy, adding to the head\'s overall security & stability; the 28mm Thicker and stronger aluminum leg tube with twist lock further enhances torsional resistance & anti-shaking on a wide variety of surfaces; the non-slip rubber feet help increase more strong friction; Metal material quick release plate durable and exquisite. You can only focus on the composition of your photo or video without worrying your hand may be shaky. 【80" Tripods & 82" Monopods】The flexible tripod with three-section aluminum legs and twist locks， you can extend the tripod from 18.5" up to 80" (extra tube for adding height to 84" inches )， which can meet various shooting needs. The three legs of the tripod can be locked separately and stabilized on varying grounds and incline levels. The travel tripod can be converted to monopod/alpenstock with a removable center column and one detachable tripod leg, 31" to 86" adjustable height. 【Heavy Duty Tripod for Camera 】 Serving as a convenient travel companion for professional photographers and passionate hobbyists alike, JOILCAN Tripod holds equipment as heavy as 35 lbs while weighing only 3.7 lbs. Compact Lightweight camera tripod with a tripod carry case makes it easy to carry for short hikes outdoor shooting and even long-distance traveling. 28 mm thickness aluminum leg tubes withstand heavier loads compared to similar camera tripods yet remain stable and flexible. 【Macro Photography Tripods 】 For added versatility of travel tripod for cameras and phones, the telescopic center column is reversible, facilitating lower-angle photography, macro shooting, and other special photography, allowing your camera to get closer to shoot the objects and magnify texture and quality.',
  'image': 'https://m.media-amazon.com/images/I/41CpH8AtYTL._AC_.jpg',
  'rating_number': 2063,
  'price': 89.99,
  'average_rating': 4.7,
  'parent_asin': 'B0BK13FTZ3'},
 {'description': 'Maxjoy AirPods Case, Military Hard Rugged Shockproof AirPods 1st and 2nd Generation Protective Case Cover with Lock Compatible with Apple Airpods 2 Gen case, Blue Camo 【Easy to Charge with Front LED Visible 】Front LED Visible design and hollow bottom design, support wire and wireless charging. Easy to charge your Airpods 1st and 2nd generation charging case without taking off the AirPods 2 Gen 【Maxjoy AirPods 2nd generation Case 】Specifically designed for your AirPods 2 Gen charging case. Maxjoy shockproof Airpods 2 protective case cover perfectly compatible with Apple AirPods Charging Case, protect your headphone against scratches and dents. Not Compatible with AirPods pro, AirPods 3 Gen 【Military AirPods 2nd Generation Case Cover with Secure Lock】 Military shockproof Airpods 2 Gen cover made of TPU and PC materials to makes the AirPods 2 case anti-shock, anti-slip and anti-fingerprint. Secure lock design, easy to open and close top cover with the open button 【Easy to Carry with Keychain】Portable travel designed Airpods 2nd generation case cover with durable black carabiner keychain. The removable keychain is easy to attach to key ring, belt or bag. Portable and practical 【Maxjoy AirPods 2nd generation Case Accessories】Package include: 1 * AirPods 2 Case with Lock for Apple AirPods case , 1 * Black Carabiner Keychain. Please kindly note AirPods 2 gen and AirPods 2 gen charging case are not included',
  'image': 'https://m.media-amazon.com/images/I/51CD1L8hlPL._AC_.jpg',
  'rating_number': 286,
  'price': 13.99,
  'average_rating': 4.5,
  'parent_asin': 'B0B6H8ZD1P'},
 {'description': "256GB Photo-Stick-for-iPhone, Apple MFi Cetified USB Flash Drive for iPhone Thumb Drive,iPhone-Memory-Stick for iPad/iPhone/Computer Picture Keeper Portable Hard Drive,Pink ✅【iOS MFi Certified Photo Stick for iPhone - Safe and Quality Assurance】This photo stick for iPhone photo storage backup certified by iOS MFi with latest lightning connector, memory stick for iPhone supports all iOS models with Lighting port ( iOS 9.0 or Above): iPhone X/ XS/ XS max/ XR/ 11/ 11pro/ X/ XS/ XR/ 12/ 12pro/ 13, iPad air/ MINI 4/ iPad/ PC etc. ★NOTE: Please remove the phone protective case before use this photo stick for iPhone flash drive. ✅【Apple Certified iPhone Photo Stick 256GB- Save Money for Extral 256GB Storage】Photo stick for Apple device with USB 3.0 for iPhone memory stick backup usb flash drive expands extra 256GB space, using this usb thumb drive, there are no more concerns about insufficient memory of iPhone/iPad. Mfi Certified flash drive guarantees fast and stable data transfers, one HD movies ( approx. 1GB) only needs about 20s. It's ideal for adding more storage to iPhone/iPad. ✅【One Click Backup USB Flash Drive Memory Stick - High Speed Transmission, Plug & Play Thumb Drive】Plug and play photo stick for iPhone, enjoy movies or musics stored in the flash drive for iPhone photo stick when you are on trip. Feel free to transfer videos and photos from iPhone/iPad to MacBook/ Windows PC/Laptops, and share your photos to social media (such as Facebook, twitter) directly from your USB 3.0 flash drive for iPhone photo stick when you take nice pictures. ✅【3-in-1 iPhone Thumb Drive for Picture Keeper and 48-Months Warranty】256GB Photo stick for iPhone flash drive with 48 Months Worry-free Warranty & dedicated email customer support. Anywhere, anytime, to resolve storage trouble, ensure faster and stable in transferring and watching. NOTE:This iPhone memory stick for phone photo stick for iPhone flash drive thumb drive photo storage backup drive DOES NOT support 12.9 inch, 11 inch for iPad Pro with USB-C port. ✅【Portable Hard Drive Photo Stick for iPhone- Protect your Privacy and Security】256GB USB flash drive for phone photo stick picture stick support file encryption. You can choose to encrypt the entire USB photo stick via fingerprints or password to secure your whole storage, or lock selected files. Perfect to protect individual privacy and your data safe on photo stick, no worry others steal your files, that you can share content while keeping sensitive files secure.",
  'image': 'https://m.media-amazon.com/images/I/41y-YsnUbPL._AC_.jpg',
  'rating_number': 151,
  'price': 29.97,
  'average_rating': 4.1,
  'parent_asin': 'B0BWRGDWNG'},

### Define the embedding function

In [16]:
co_client = cohere.Client(api_key=os.environ.get("COHERE_API_KEY"))
# Test the Cohere embedding model
response = co_client.embed(
    texts=["Random text"],
    model="embed-english-v3.0",
    input_type="search_document"
)
# Print the first few numbers to verify it worked
print(response.embeddings[0][:5])

[-0.014183044, 0.0037727356, 0.005558014, -0.017471313, -0.037322998]

In [18]:
len(response.embeddings[0])

1024

In [19]:
# The Cohere version of your teacher's function
def get_embedding(text, model="embed-english-v3.0"):
    response = co_client.embed(
        texts=[text],
        model=model,
        input_type="search_query"
    )
    return response.embeddings[0]
get_embedding("Hello world!")

[-0.03829956,
 -0.047210693,
 -0.08502197,
 -0.08239746,
 -0.008659363,
 0.0009498596,
 -0.04425049,
 0.066467285,
 0.011169434,
 0.014572144,
 -0.030670166,
 0.03543091,
 0.049072266,
 -0.04724121,
 0.051757812,
 -0.028213501,
 0.0491333,
 0.007873535,
 -0.010040283,
 -0.009513855,
 -0.019241333,
 0.014251709,
 0.011474609,
 0.017791748,
 0.044952393,
 -0.008796692,
 0.004055023,
 -0.0014390945,
 -0.058685303,
 -0.043060303,
 -0.007385254,
 0.060424805,
 0.019363403,
 0.024154663,
 -0.009483337,
 0.037261963,
 -0.018676758,
 0.006378174,
 0.010848999,
 -0.0011062622,
 0.015357971,
 -0.0018415451,
 0.012664795,
 -0.039855957,
 -0.030059814,
 0.0019159317,
 -0.040924072,
 -0.0104522705,
 0.03942871,
 -0.029159546,
 0.007686615,
 -0.012924194,
 -0.00027561188,
 0.009880066,
 -0.0062942505,
 0.007118225,
 -0.046142578,
 -0.009513855,
 0.009811401,
 0.07287598,
 0.025146484,
 0.0074005127,
 0.003440857,
 -0.013320923,
 0.010414124,
 0.0021324158,
 0.013366699,
 0.011276245,
 0.0289917,
 0.029037476,
 -0.0016098022,
 0.015319824,
 -0.015060425,
 -0.02670288,
 0.0016412735,
 0.018600464,
 -0.027023315,
 0.016906738,
 0.025909424,
 0.019714355,
 0.02619934,
 0.016357422,
 -0.0028133392,
 -0.0579834,
 0.012283325,
 -0.035491943,
 -0.011734009,
 0.0005173683,
 0.006652832,
 -0.05038452,
 -0.0032215118,
 0.054718018,
 -0.018753052,
 -0.023071289,
 -0.060699463,
 -0.010604858,
 -0.011993408,
 0.035491943,
 0.0006375313,
 0.037719727,
 -0.015312195,
 -0.013771057,
 0.0015525818,
 -0.031021118,
 -0.0021152496,
 -0.0104522705,
 -0.025650024,
 0.005584717,
 0.027770996,
 0.04107666,
 -0.021118164,
 0.049621582,
 -0.00579834,
 0.0072898865,
 -0.0206604,
 -0.0055885315,
 -0.003534317,
 0.01436615,
 0.0053482056,
 0.035003662,
 0.025024414,
 0.03390503,
 0.008773804,
 0.009979248,
 -0.0057411194,
 -0.0011787415,
 -0.042938232,
 -0.02230835,
 0.06591797,
 -0.032318115,
 0.005836487,
 0.06591797,
 -0.08239746,
 -0.055358887,
 -0.035186768,
 0.025039673,
 0.035308838,
 -0.033477783,
 0.026657104,
 0.018722534,
 0.04534912,
 -0.007896423,
 0.020477295,
 0.023452759,
 -0.031402588,
 0.02355957,
 0.0064315796,
 -0.009300232,
 -0.009277344,
 -0.017913818,
 -0.0390625,
 -0.023483276,
 0.0012607574,
 0.0029010773,
 0.022644043,
 0.008460999,
 -0.046539307,
 0.016555786,
 0.028839111,
 0.046813965,
 -0.032165527,
 0.01424408,
 0.05441284,
 -0.049957275,
 -0.0158844,
 -0.045043945,
 -0.050567627,
 0.005710602,
 -0.006351471,
 0.022750854,
 -0.006275177,
 0.016357422,
 0.0051345825,
 0.009239197,
 0.0046806335,
 0.002532959,
 -0.013664246,
 0.014945984,
 0.0010213852,
 0.10650635,
 0.05328369,
 -0.009010315,
 -0.040618896,
 0.08270264,
 -0.0022010803,
 -0.019454956,
 -0.0129470825,
 -0.035583496,
 0.056671143,
 -0.014907837,
 0.044921875,
 -0.016113281,
 -0.07989502,
 0.029220581,
 -0.013725281,
 -0.029647827,
 0.009498596,
 0.00035572052,
 -0.014541626,
 -0.0016546249,
 -0.0016670227,
 -0.0037879944,
 0.012283325,
 -0.025314331,
 0.023590088,
 -0.01889038,
 0.003156662,
 0.023071289,
 0.010772705,
 0.014389038,
 -0.02494812,
 -0.033599854,
 0.026824951,
 -0.087768555,
 -0.032806396,
 -0.018707275,
 -0.04534912,
 0.051330566,
 0.022018433,
 0.01902771,
 0.028442383,
 -0.04296875,
 0.009963989,
 -0.016448975,
 0.0047302246,
 0.0284729,
 -0.044677734,
 0.013435364,
 -0.036010742,
 0.006511688,
 -0.030380249,
 0.023223877,
 -0.070007324,
 -0.037139893,
 -0.048217773,
 -0.041503906,
 -0.08068848,
 0.01083374,
 0.0033740997,
 0.03778076,
 0.025100708,
 0.00052404404,
 -0.02607727,
 -0.009063721,
 0.028411865,
 -4.7683716e-07,
 0.032318115,
 -0.007106781,
 0.033721924,
 0.037506104,
 0.035095215,
 0.03036499,
 0.030639648,
 -0.005924225,
 -0.005886078,
 0.079711914,
 -0.021469116,
 0.009605408,
 -0.0087890625,
 0.014762878,
 -0.02041626,
 0.014472961,
 0.0116119385,
 -0.0032806396,
 -0.036224365,
 -0.010810852,
 -0.034729004,
 -0.026626587,
 -0.004459381,
 -0.007987976,
 0.031341553,
 -0.037200928,
 -0.009056091,
 -0.014381409,
 0.046783447,
 -0.029006958,
 -0.07537842,
 0.024841309,
 0.011711121,
 -0.021484375,
 -0.013626099,
 -0.01687622,
 0.004676819,
 0.002779007,
 0.036346436,
 -0.020233154,
 0.009849548,
 0.029296875,
 0.025756836,
 0.056121826,
 0.07208252,
 0.012245178,
 0.0064353943,
 0.041046143,
 -0.023071289,
 -0.007648468,
 0.039733887,
 0.07159424,
 -0.03149414,
 0.009933472,
 -0.017456055,
 -0.002632141,
 0.005844116,
 -0.032165527,
 -0.00094747543,
 -0.02848816,
 -0.017822266,
 0.017044067,
 0.030044556,
 -0.0010519028,
 -0.028457642,
 0.052093506,
 0.012054443,
 -0.0041885376,
 -0.042022705,
 -0.050109863,
 -0.023330688,
 -0.005168915,
 -0.13574219,
 -0.07336426,
 -0.027938843,
 -0.017730713,
 0.012840271,
 -0.020523071,
 -0.00466156,
 -0.019073486,
 -0.031097412,
 0.008552551,
 -0.0006289482,
 -0.034332275,
 0.027297974,
 0.0048446655,
 -0.02545166,
 0.015975952,
 0.02760315,
 -0.0022296906,
 0.05279541,
 -0.045013428,
 0.01399231,
 -0.0011920929,
 0.08099365,
 -0.04852295,
 0.003271103,
 0.011222839,
 0.016326904,
 -0.023757935,
 0.0014266968,
 0.0012559891,
 0.045562744,
 0.014274597,
 -0.008766174,
 -0.028671265,
 0.011100769,
 -0.0059814453,
 0.011871338,
 -0.04559326,
 -0.040771484,
 -0.05883789,
 -0.016525269,
 -0.08074951,
 0.018417358,
 0.0256958,
 -0.0124435425,
 -0.014144897,
 -0.03656006,
 -0.018722534,
 0.023239136,
 0.010391235,
 -0.051361084,
 0.010131836,
 0.0029964447,
 -0.018051147,
 0.022644043,
 -0.04397583,
 -0.07086182,
 0.0211792,
 0.007499695,
 -0.038024902,
 0.010124207,
 0.009223938,
 0.01991272,
 0.034973145,
 -0.018875122,
 0.033416748,
 0.034729004,
 0.015106201,
 -0.0069618225,
 -0.01158905,
 0.05529785,
 0.035980225,
 0.021850586,
 0.008087158,
 -0.038482666,
 0.0028762817,
 0.038879395,
 0.016311646,
 -0.059783936,
 0.026443481,
 -0.11553955,
 0.01638794,
 -0.031982422,
 0.017807007,
 0.007774353,
 0.0044898987,
 -0.056396484,
 0.025726318,
 -0.032470703,
 -0.008399963,
 -0.0017356873,
 0.04724121,
 0.040496826,
 -0.021392822,
 0.011230469,
 0.007911682,
 -0.00034356117,
 -0.017242432,
 -0.082214355,
 -0.013641357,
 0.018249512,
 0.012901306,
 -0.037628174,
 0.055786133,
 -0.051818848,
 0.0067825317,
 -0.02734375,
 0.018676758,
 -0.019607544,
 0.026138306,
 0.004928589,
 0.0033874512,
 0.021408081,
 -0.032440186,
 -0.019348145,
 -0.042388916,
 -0.052368164,
 0.029281616,
 -0.007801056,
 0.015411377,
 -0.008682251,
 -0.015472412,
 -0.0024719238,
 -0.0011634827,
 0.015144348,
 -0.0022602081,
 0.0066490173,
 -0.00434494,
 -0.0062408447,
 0.0546875,
 -0.064208984,
 -0.011917114,
 -0.057037354,
 0.03704834,
 -0.03552246,
 0.056549072,
 0.014122009,
 0.008522034,
 0.03164673,
 0.03970337,
 0.049865723,
 -0.0074539185,
 -0.013061523,
 0.0022392273,
 -0.038848877,
 -0.013870239,
 0.00054740906,
 -0.016586304,
 0.08099365,
 -0.007080078,
 -0.026992798,
 0.01159668,
 -0.026901245,
 -0.0013771057,
 0.02798462,
 0.033111572,
 -0.0066833496,
 0.0027389526,
 -0.033416748,
 0.036621094,
 -0.039123535,
 0.037078857,
 -0.022872925,
 0.014579773,
 -0.0158844,
 -0.025009155,
 -0.03036499,
 0.020401001,
 -0.057617188,
 -0.07165527,
 0.013343811,
 0.05532837,
 0.0340271,
 -0.032806396,
 0.04953003,
 0.033996582,
 -0.03753662,
 0.025161743,
 -0.016616821,
 0.041168213,
 0.011268616,
 -0.012992859,
 -0.028305054,
 -0.02281189,
 -0.0026130676,
 0.0040893555,
 0.041931152,
 -0.025802612,
 -0.01928711,
 0.009521484,
 0.0024147034,
 0.066711426,
 0.010925293,
 -0.0045318604,
 0.002603531,
 0.02848816,
 -0.00058460236,
 0.045898438,
 -0.04171753,
 0.01335907,
 -0.014701843,
 -0.014450073,
 -0.0056114197,
 -0.0014925003,
 0.019851685,
 0.02784729,
 -0.023635864,
 0.009063721,
 -0.023498535,
 -0.009254456,
 -0.002292633,
 -0.056030273,
 0.055908203,
 0.027709961,
 0.016555786,
 0.02507019,
 -0.023223877,
 0.04434204,
 -0.057250977,
 0.0012397766,
 0.0023212433,
 -0.01586914,
 0.0001835823,
 0.016052246,
 0.0069465637,
 -0.0013227463,
 0.004184723,
 0.031219482,
 0.03564453,
 0.059387207,
 -0.06036377,
 0.06542969,
 -0.015899658,
 -0.016464233,
 0.014511108,
 0.010505676,
 -0.010360718,
 -0.049987793,
 -0.036834717,
 -0.0042381287,
 0.0068969727,
 0.06335449,
 -0.016403198,
 0.00061130524,
 -0.032470703,
 -0.0009675026,
 -0.0335083,
 0.008529663,
 -0.006336212,
 -0.008415222,
 0.012672424,
 -0.02859497,
 -0.06161499,
 -0.07128906,
 -0.051818848,
 -0.009963989,
 -0.05819702,
 0.049041748,
 0.00083589554,
 0.025131226,
 0.018356323,
 0.08093262,
 0.0067100525,
 0.015274048,
 -0.03286743,
 0.03086853,
 -0.02670288,
 0.048736572,
 0.016983032,
 0.033172607,
 -0.0013170242,
 0.018203735,
 -0.018875122,
 -0.02507019,
 -0.021102905,
 -0.0025539398,
 0.033111572,
 0.02041626,
 0.004623413,
 -0.043029785,
 0.03878784,
 0.01096344,
 -0.036834717,
 0.0059776306,
 0.019302368,
 -0.018051147,
 0.0007209778,
 0.004589081,
 -0.0317688,
 -0.02180481,
 -0.00390625,
 -0.03955078,
 0.03918457,
 -0.027236938,
 -0.0043563843,
 0.022857666,
 -0.01625061,
 -0.011108398,
 0.00504303,
 0.02645874,
 0.00015592575,
 -0.026977539,
 0.008651733,
 -0.048034668,
 0.03201294,
 0.010025024,
 0.030334473,
 -0.0010147095,
 0.026916504,
 0.012954712,
 -0.010536194,
 0.010932922,
 0.003824234,
 0.011695862,
 -0.014305115,
 -0.019577026,
 0.0121536255,
 0.07080078,
 -0.036193848,
 -0.011543274,
 -0.08123779,
 -0.046051025,
 0.026428223,
 0.009132385,
 0.022628784,
 -0.0340271,
 -0.0020503998,
 0.0007314682,
 -0.010108948,
 -0.009490967,
 -0.041625977,
 -0.016952515,
 -0.012298584,
 0.0056152344,
 -0.031234741,
 0.025756836,
 -0.029159546,
 -0.0073280334,
 0.0340271,
 0.058044434,
 -0.0052757263,
 -0.01725769,
 -0.06689453,
 -0.017486572,
 -0.03427124,
 -0.048706055,
 0.019515991,
 0.0042877197,
 0.014274597,
 0.054016113,
 -0.03503418,
 0.06591797,
 0.003660202,
 0.0048446655,
 0.032409668,
 -0.002981186,
 -0.049316406,
 -0.017990112,
 0.041381836,
 -0.013427734,
 -0.0049552917,
 -0.0043945312,
 -0.0038375854,
 0.01084137,
 0.011940002,
 0.016494751,
 -0.0206604,
 0.036621094,
 0.016586304,
 -0.005191803,
 0.009994507,
 -0.022705078,
 -0.053222656,
 -0.010765076,
 -0.013656616,
 -0.023010254,
 0.06536865,
 -0.0038528442,
 -0.039398193,
 -0.039733887,
 0.0003106594,
 0.0013332367,
 -0.005580902,
 -0.023086548,
 0.029510498,
 -0.054229736,
 0.005710602,
 0.0030441284,
 0.024337769,
 0.02130127,
 -0.0023479462,
 -0.01676941,
 0.017074585,
 0.029907227,
 -0.07446289,
 -0.031234741,
 0.028244019,
 -0.06097412,
 -0.046447754,
 -0.029144287,
 -0.025497437,
 0.018051147,
 -0.022781372,
 -0.04736328,
 0.00066947937,
 -0.03918457,
 0.013824463,
 -0.028778076,
 -0.031829834,
 0.0011281967,
 0.007896423,
 0.0005893707,
 0.032226562,
 0.03277588,
 -0.030914307,
 0.015792847,
 0.0013599396,
 0.033935547,
 0.024047852,
 0.020050049,
 0.039001465,
 -0.0042533875,
 -0.06976318,
 0.00057554245,
 0.024932861,
 0.010055542,
 -0.0010147095,
 0.021713257,
 0.010818481,
 0.024551392,
 -0.0071983337,
 0.009605408,
 0.0042533875,
 0.005466461,
 0.056243896,
 0.024856567,
 0.016906738,
 -0.029815674,
 -0.025222778,
 0.033294678,
 0.0680542,
 -0.046966553,
 -0.065979004,
 -0.025527954,
 -0.012962341,
 0.070495605,
 0.018920898,
 0.07739258,
 0.04663086,
 0.03036499,
 -0.024627686,
 0.023834229,
 0.059265137,
 -0.011657715,
 0.007621765,
 -7.611513e-05,
 -0.015342712,
 0.049865723,
 0.015701294,
 -0.004371643,
 -0.015792847,
 0.009506226,
 -0.0012369156,
 0.005847931,
 -0.037078857,
 -0.0017414093,
 -0.030731201,
 -0.0049209595,
 0.05218506,
 0.02217102,
 0.014831543,
 0.083984375,
 -0.004699707,
 0.026901245,
 -0.010932922,
 0.05996704,
 0.02015686,
 -0.018035889,
 0.017364502,
 -0.004558563,
 0.028030396,
 -0.036193848,
 0.00044178963,
 0.04244995,
 -0.039489746,
 0.0068244934,
 -0.038482666,
 -0.03994751,
 0.041625977,
 0.014709473,
 -0.030395508,
 0.043762207,
 0.0059051514,
 -0.04925537,
 0.00484848,
 -0.0036582947,
 0.026443481,
 -0.018737793,
 0.024993896,
 0.0012493134,
 0.005809784,
 -0.074645996,
 -0.0027313232,
 0.03778076,
 0.010299683,
 -0.016204834,
 -0.017242432,
 0.027801514,
 0.02609253,
 -0.02116394,
 -0.02230835,
 -0.020828247,
 0.041046143,
 -0.01386261,
 -0.008125305,
 -0.00053215027,
 -0.0027828217,
 0.0002834797,
 0.06384277,
 -0.014129639,
 0.030258179,
 0.01259613,
 -0.04083252,
 -0.0052490234,
 -0.024551392,
 -0.014038086,
 -0.050476074,
 0.01687622,
 0.026885986,
 -0.027374268,
 0.007980347,
 0.033294678,
 0.04650879,
 0.020492554,
 0.012870789,
 -0.009216309,
 0.0069732666,
 0.0070724487,
 -0.0058784485,
 -0.030670166,
 -0.021118164,
 -0.015625,
 -0.011123657,
 -0.0027046204,
 0.03378296,
 0.023010254,
 0.03427124,
 0.0146865845,
 -0.038146973,
 0.012420654,
 -0.017425537,
 -0.012252808,
 0.0019893646,
 0.020568848,
 0.012107849,
 -0.051940918,
 -0.028747559,
 0.004753113,
 -0.017211914,
 7.402897e-05,
 -0.024032593,
 0.07312012,
 0.032287598,
 0.017166138,
 -0.011688232,
 -0.09063721,
 -0.018539429,
 0.047698975,
 -0.023147583,
 0.017349243,
 0.023239136,
 0.016494751,
 0.0262146,
 -0.06222534,
 -0.03050232,
 0.006046295,
 -0.04336548,
 5.9962273e-05,
 -0.05319214,
 0.007762909,
 -0.013641357,
 0.04586792,
 -0.05670166,
 -0.04510498,
 -0.012313843,
 0.013412476,
 -0.019683838,
 -0.0041503906,
 -0.010101318,
 -0.0040359497,
 -0.017456055,
 -0.023727417,
 0.045928955,
 -0.0033111572,
 0.0027236938,
 0.0340271,
 -0.026763916,
 -0.0030002594,
 -0.046844482,
 0.0039863586,
 -0.0009636879,
 -0.06732178,
 -0.0071792603,
 0.019195557,
 -0.025619507,
 -0.008575439,
 -0.027038574,
 0.009613037,
 -0.042999268,
 -0.026748657,
 -0.018081665,
 -0.022476196,
 -0.038848877,
 -0.03378296,
 -0.0657959,
 -0.033294678,
 -0.0054740906,
 -0.043640137,
 0.020233154,
 -0.029388428,
 -0.03152466,
 0.051971436,
 0.015342712,
 -0.013442993,
 0.008163452,
 0.030578613,
 -0.017578125,
 0.015838623,
 0.017547607,
 0.0039367676,
 -0.006816864,
 0.014060974,
 0.015701294,
 -0.031036377,
 -0.043395996,
 -0.0027332306,
 0.0029582977,
 0.040649414,
 -0.042236328,
 0.00447464,
 0.0041999817,
 0.01802063,
 -0.0007033348,
 0.004878998,
 0.01852417,
 0.00097084045,
 -0.02760315,
 0.01374054,
 -0.022644043,
 -0.02671814,
 -0.005542755,
 -0.031341553,
 -0.025970459,
 -0.025115967,
 0.014266968,
 -0.03829956,
 0.00061130524,
 0.008148193,
 0.025314331,
 -0.0058517456,
 0.005897522,
 0.024551392,
 -0.057525635,
 0.031082153,
 -0.0335083,
 0.016174316,
 -0.04525757,
 0.076416016,
 -0.060272217,
 -0.046051025,
 0.015625,
 0.025146484,
 0.03152466,
 0.03845215,
 -0.03555298,
 -0.015037537,
 0.051513672,
 0.014762878,
 0.015083313,
 0.00038790703,
 0.051239014,
 0.029815674,
 ...]

In [20]:
get_embedding("Hello world!")

[-0.03829956,
 -0.047210693,
 -0.08502197,
 -0.08239746,
 -0.008659363,
 0.0009498596,
 -0.04425049,
 0.066467285,
 0.011169434,
 0.014572144,
 -0.030670166,
 0.03543091,
 0.049072266,
 -0.04724121,
 0.051757812,
 -0.028213501,
 0.0491333,
 0.007873535,
 -0.010040283,
 -0.009513855,
 -0.019241333,
 0.014251709,
 0.011474609,
 0.017791748,
 0.044952393,
 -0.008796692,
 0.004055023,
 -0.0014390945,
 -0.058685303,
 -0.043060303,
 -0.007385254,
 0.060424805,
 0.019363403,
 0.024154663,
 -0.009483337,
 0.037261963,
 -0.018676758,
 0.006378174,
 0.010848999,
 -0.0011062622,
 0.015357971,
 -0.0018415451,
 0.012664795,
 -0.039855957,
 -0.030059814,
 0.0019159317,
 -0.040924072,
 -0.0104522705,
 0.03942871,
 -0.029159546,
 0.007686615,
 -0.012924194,
 -0.00027561188,
 0.009880066,
 -0.0062942505,
 0.007118225,
 -0.046142578,
 -0.009513855,
 0.009811401,
 0.07287598,
 0.025146484,
 0.0074005127,
 0.003440857,
 -0.013320923,
 0.010414124,
 0.0021324158,
 0.013366699,
 0.011276245,
 0.0289917,
 0.029037476,
 -0.0016098022,
 0.015319824,
 -0.015060425,
 -0.02670288,
 0.0016412735,
 0.018600464,
 -0.027023315,
 0.016906738,
 0.025909424,
 0.019714355,
 0.02619934,
 0.016357422,
 -0.0028133392,
 -0.0579834,
 0.012283325,
 -0.035491943,
 -0.011734009,
 0.0005173683,
 0.006652832,
 -0.05038452,
 -0.0032215118,
 0.054718018,
 -0.018753052,
 -0.023071289,
 -0.060699463,
 -0.010604858,
 -0.011993408,
 0.035491943,
 0.0006375313,
 0.037719727,
 -0.015312195,
 -0.013771057,
 0.0015525818,
 -0.031021118,
 -0.0021152496,
 -0.0104522705,
 -0.025650024,
 0.005584717,
 0.027770996,
 0.04107666,
 -0.021118164,
 0.049621582,
 -0.00579834,
 0.0072898865,
 -0.0206604,
 -0.0055885315,
 -0.003534317,
 0.01436615,
 0.0053482056,
 0.035003662,
 0.025024414,
 0.03390503,
 0.008773804,
 0.009979248,
 -0.0057411194,
 -0.0011787415,
 -0.042938232,
 -0.02230835,
 0.06591797,
 -0.032318115,
 0.005836487,
 0.06591797,
 -0.08239746,
 -0.055358887,
 -0.035186768,
 0.025039673,
 0.035308838,
 -0.033477783,
 0.026657104,
 0.018722534,
 0.04534912,
 -0.007896423,
 0.020477295,
 0.023452759,
 -0.031402588,
 0.02355957,
 0.0064315796,
 -0.009300232,
 -0.009277344,
 -0.017913818,
 -0.0390625,
 -0.023483276,
 0.0012607574,
 0.0029010773,
 0.022644043,
 0.008460999,
 -0.046539307,
 0.016555786,
 0.028839111,
 0.046813965,
 -0.032165527,
 0.01424408,
 0.05441284,
 -0.049957275,
 -0.0158844,
 -0.045043945,
 -0.050567627,
 0.005710602,
 -0.006351471,
 0.022750854,
 -0.006275177,
 0.016357422,
 0.0051345825,
 0.009239197,
 0.0046806335,
 0.002532959,
 -0.013664246,
 0.014945984,
 0.0010213852,
 0.10650635,
 0.05328369,
 -0.009010315,
 -0.040618896,
 0.08270264,
 -0.0022010803,
 -0.019454956,
 -0.0129470825,
 -0.035583496,
 0.056671143,
 -0.014907837,
 0.044921875,
 -0.016113281,
 -0.07989502,
 0.029220581,
 -0.013725281,
 -0.029647827,
 0.009498596,
 0.00035572052,
 -0.014541626,
 -0.0016546249,
 -0.0016670227,
 -0.0037879944,
 0.012283325,
 -0.025314331,
 0.023590088,
 -0.01889038,
 0.003156662,
 0.023071289,
 0.010772705,
 0.014389038,
 -0.02494812,
 -0.033599854,
 0.026824951,
 -0.087768555,
 -0.032806396,
 -0.018707275,
 -0.04534912,
 0.051330566,
 0.022018433,
 0.01902771,
 0.028442383,
 -0.04296875,
 0.009963989,
 -0.016448975,
 0.0047302246,
 0.0284729,
 -0.044677734,
 0.013435364,
 -0.036010742,
 0.006511688,
 -0.030380249,
 0.023223877,
 -0.070007324,
 -0.037139893,
 -0.048217773,
 -0.041503906,
 -0.08068848,
 0.01083374,
 0.0033740997,
 0.03778076,
 0.025100708,
 0.00052404404,
 -0.02607727,
 -0.009063721,
 0.028411865,
 -4.7683716e-07,
 0.032318115,
 -0.007106781,
 0.033721924,
 0.037506104,
 0.035095215,
 0.03036499,
 0.030639648,
 -0.005924225,
 -0.005886078,
 0.079711914,
 -0.021469116,
 0.009605408,
 -0.0087890625,
 0.014762878,
 -0.02041626,
 0.014472961,
 0.0116119385,
 -0.0032806396,
 -0.036224365,
 -0.010810852,
 -0.034729004,
 -0.026626587,
 -0.004459381,
 -0.007987976,
 0.031341553,
 -0.037200928,
 -0.009056091,
 -0.014381409,
 0.046783447,
 -0.029006958,
 -0.07537842,
 0.024841309,
 0.011711121,
 -0.021484375,
 -0.013626099,
 -0.01687622,
 0.004676819,
 0.002779007,
 0.036346436,
 -0.020233154,
 0.009849548,
 0.029296875,
 0.025756836,
 0.056121826,
 0.07208252,
 0.012245178,
 0.0064353943,
 0.041046143,
 -0.023071289,
 -0.007648468,
 0.039733887,
 0.07159424,
 -0.03149414,
 0.009933472,
 -0.017456055,
 -0.002632141,
 0.005844116,
 -0.032165527,
 -0.00094747543,
 -0.02848816,
 -0.017822266,
 0.017044067,
 0.030044556,
 -0.0010519028,
 -0.028457642,
 0.052093506,
 0.012054443,
 -0.0041885376,
 -0.042022705,
 -0.050109863,
 -0.023330688,
 -0.005168915,
 -0.13574219,
 -0.07336426,
 -0.027938843,
 -0.017730713,
 0.012840271,
 -0.020523071,
 -0.00466156,
 -0.019073486,
 -0.031097412,
 0.008552551,
 -0.0006289482,
 -0.034332275,
 0.027297974,
 0.0048446655,
 -0.02545166,
 0.015975952,
 0.02760315,
 -0.0022296906,
 0.05279541,
 -0.045013428,
 0.01399231,
 -0.0011920929,
 0.08099365,
 -0.04852295,
 0.003271103,
 0.011222839,
 0.016326904,
 -0.023757935,
 0.0014266968,
 0.0012559891,
 0.045562744,
 0.014274597,
 -0.008766174,
 -0.028671265,
 0.011100769,
 -0.0059814453,
 0.011871338,
 -0.04559326,
 -0.040771484,
 -0.05883789,
 -0.016525269,
 -0.08074951,
 0.018417358,
 0.0256958,
 -0.0124435425,
 -0.014144897,
 -0.03656006,
 -0.018722534,
 0.023239136,
 0.010391235,
 -0.051361084,
 0.010131836,
 0.0029964447,
 -0.018051147,
 0.022644043,
 -0.04397583,
 -0.07086182,
 0.0211792,
 0.007499695,
 -0.038024902,
 0.010124207,
 0.009223938,
 0.01991272,
 0.034973145,
 -0.018875122,
 0.033416748,
 0.034729004,
 0.015106201,
 -0.0069618225,
 -0.01158905,
 0.05529785,
 0.035980225,
 0.021850586,
 0.008087158,
 -0.038482666,
 0.0028762817,
 0.038879395,
 0.016311646,
 -0.059783936,
 0.026443481,
 -0.11553955,
 0.01638794,
 -0.031982422,
 0.017807007,
 0.007774353,
 0.0044898987,
 -0.056396484,
 0.025726318,
 -0.032470703,
 -0.008399963,
 -0.0017356873,
 0.04724121,
 0.040496826,
 -0.021392822,
 0.011230469,
 0.007911682,
 -0.00034356117,
 -0.017242432,
 -0.082214355,
 -0.013641357,
 0.018249512,
 0.012901306,
 -0.037628174,
 0.055786133,
 -0.051818848,
 0.0067825317,
 -0.02734375,
 0.018676758,
 -0.019607544,
 0.026138306,
 0.004928589,
 0.0033874512,
 0.021408081,
 -0.032440186,
 -0.019348145,
 -0.042388916,
 -0.052368164,
 0.029281616,
 -0.007801056,
 0.015411377,
 -0.008682251,
 -0.015472412,
 -0.0024719238,
 -0.0011634827,
 0.015144348,
 -0.0022602081,
 0.0066490173,
 -0.00434494,
 -0.0062408447,
 0.0546875,
 -0.064208984,
 -0.011917114,
 -0.057037354,
 0.03704834,
 -0.03552246,
 0.056549072,
 0.014122009,
 0.008522034,
 0.03164673,
 0.03970337,
 0.049865723,
 -0.0074539185,
 -0.013061523,
 0.0022392273,
 -0.038848877,
 -0.013870239,
 0.00054740906,
 -0.016586304,
 0.08099365,
 -0.007080078,
 -0.026992798,
 0.01159668,
 -0.026901245,
 -0.0013771057,
 0.02798462,
 0.033111572,
 -0.0066833496,
 0.0027389526,
 -0.033416748,
 0.036621094,
 -0.039123535,
 0.037078857,
 -0.022872925,
 0.014579773,
 -0.0158844,
 -0.025009155,
 -0.03036499,
 0.020401001,
 -0.057617188,
 -0.07165527,
 0.013343811,
 0.05532837,
 0.0340271,
 -0.032806396,
 0.04953003,
 0.033996582,
 -0.03753662,
 0.025161743,
 -0.016616821,
 0.041168213,
 0.011268616,
 -0.012992859,
 -0.028305054,
 -0.02281189,
 -0.0026130676,
 0.0040893555,
 0.041931152,
 -0.025802612,
 -0.01928711,
 0.009521484,
 0.0024147034,
 0.066711426,
 0.010925293,
 -0.0045318604,
 0.002603531,
 0.02848816,
 -0.00058460236,
 0.045898438,
 -0.04171753,
 0.01335907,
 -0.014701843,
 -0.014450073,
 -0.0056114197,
 -0.0014925003,
 0.019851685,
 0.02784729,
 -0.023635864,
 0.009063721,
 -0.023498535,
 -0.009254456,
 -0.002292633,
 -0.056030273,
 0.055908203,
 0.027709961,
 0.016555786,
 0.02507019,
 -0.023223877,
 0.04434204,
 -0.057250977,
 0.0012397766,
 0.0023212433,
 -0.01586914,
 0.0001835823,
 0.016052246,
 0.0069465637,
 -0.0013227463,
 0.004184723,
 0.031219482,
 0.03564453,
 0.059387207,
 -0.06036377,
 0.06542969,
 -0.015899658,
 -0.016464233,
 0.014511108,
 0.010505676,
 -0.010360718,
 -0.049987793,
 -0.036834717,
 -0.0042381287,
 0.0068969727,
 0.06335449,
 -0.016403198,
 0.00061130524,
 -0.032470703,
 -0.0009675026,
 -0.0335083,
 0.008529663,
 -0.006336212,
 -0.008415222,
 0.012672424,
 -0.02859497,
 -0.06161499,
 -0.07128906,
 -0.051818848,
 -0.009963989,
 -0.05819702,
 0.049041748,
 0.00083589554,
 0.025131226,
 0.018356323,
 0.08093262,
 0.0067100525,
 0.015274048,
 -0.03286743,
 0.03086853,
 -0.02670288,
 0.048736572,
 0.016983032,
 0.033172607,
 -0.0013170242,
 0.018203735,
 -0.018875122,
 -0.02507019,
 -0.021102905,
 -0.0025539398,
 0.033111572,
 0.02041626,
 0.004623413,
 -0.043029785,
 0.03878784,
 0.01096344,
 -0.036834717,
 0.0059776306,
 0.019302368,
 -0.018051147,
 0.0007209778,
 0.004589081,
 -0.0317688,
 -0.02180481,
 -0.00390625,
 -0.03955078,
 0.03918457,
 -0.027236938,
 -0.0043563843,
 0.022857666,
 -0.01625061,
 -0.011108398,
 0.00504303,
 0.02645874,
 0.00015592575,
 -0.026977539,
 0.008651733,
 -0.048034668,
 0.03201294,
 0.010025024,
 0.030334473,
 -0.0010147095,
 0.026916504,
 0.012954712,
 -0.010536194,
 0.010932922,
 0.003824234,
 0.011695862,
 -0.014305115,
 -0.019577026,
 0.0121536255,
 0.07080078,
 -0.036193848,
 -0.011543274,
 -0.08123779,
 -0.046051025,
 0.026428223,
 0.009132385,
 0.022628784,
 -0.0340271,
 -0.0020503998,
 0.0007314682,
 -0.010108948,
 -0.009490967,
 -0.041625977,
 -0.016952515,
 -0.012298584,
 0.0056152344,
 -0.031234741,
 0.025756836,
 -0.029159546,
 -0.0073280334,
 0.0340271,
 0.058044434,
 -0.0052757263,
 -0.01725769,
 -0.06689453,
 -0.017486572,
 -0.03427124,
 -0.048706055,
 0.019515991,
 0.0042877197,
 0.014274597,
 0.054016113,
 -0.03503418,
 0.06591797,
 0.003660202,
 0.0048446655,
 0.032409668,
 -0.002981186,
 -0.049316406,
 -0.017990112,
 0.041381836,
 -0.013427734,
 -0.0049552917,
 -0.0043945312,
 -0.0038375854,
 0.01084137,
 0.011940002,
 0.016494751,
 -0.0206604,
 0.036621094,
 0.016586304,
 -0.005191803,
 0.009994507,
 -0.022705078,
 -0.053222656,
 -0.010765076,
 -0.013656616,
 -0.023010254,
 0.06536865,
 -0.0038528442,
 -0.039398193,
 -0.039733887,
 0.0003106594,
 0.0013332367,
 -0.005580902,
 -0.023086548,
 0.029510498,
 -0.054229736,
 0.005710602,
 0.0030441284,
 0.024337769,
 0.02130127,
 -0.0023479462,
 -0.01676941,
 0.017074585,
 0.029907227,
 -0.07446289,
 -0.031234741,
 0.028244019,
 -0.06097412,
 -0.046447754,
 -0.029144287,
 -0.025497437,
 0.018051147,
 -0.022781372,
 -0.04736328,
 0.00066947937,
 -0.03918457,
 0.013824463,
 -0.028778076,
 -0.031829834,
 0.0011281967,
 0.007896423,
 0.0005893707,
 0.032226562,
 0.03277588,
 -0.030914307,
 0.015792847,
 0.0013599396,
 0.033935547,
 0.024047852,
 0.020050049,
 0.039001465,
 -0.0042533875,
 -0.06976318,
 0.00057554245,
 0.024932861,
 0.010055542,
 -0.0010147095,
 0.021713257,
 0.010818481,
 0.024551392,
 -0.0071983337,
 0.009605408,
 0.0042533875,
 0.005466461,
 0.056243896,
 0.024856567,
 0.016906738,
 -0.029815674,
 -0.025222778,
 0.033294678,
 0.0680542,
 -0.046966553,
 -0.065979004,
 -0.025527954,
 -0.012962341,
 0.070495605,
 0.018920898,
 0.07739258,
 0.04663086,
 0.03036499,
 -0.024627686,
 0.023834229,
 0.059265137,
 -0.011657715,
 0.007621765,
 -7.611513e-05,
 -0.015342712,
 0.049865723,
 0.015701294,
 -0.004371643,
 -0.015792847,
 0.009506226,
 -0.0012369156,
 0.005847931,
 -0.037078857,
 -0.0017414093,
 -0.030731201,
 -0.0049209595,
 0.05218506,
 0.02217102,
 0.014831543,
 0.083984375,
 -0.004699707,
 0.026901245,
 -0.010932922,
 0.05996704,
 0.02015686,
 -0.018035889,
 0.017364502,
 -0.004558563,
 0.028030396,
 -0.036193848,
 0.00044178963,
 0.04244995,
 -0.039489746,
 0.0068244934,
 -0.038482666,
 -0.03994751,
 0.041625977,
 0.014709473,
 -0.030395508,
 0.043762207,
 0.0059051514,
 -0.04925537,
 0.00484848,
 -0.0036582947,
 0.026443481,
 -0.018737793,
 0.024993896,
 0.0012493134,
 0.005809784,
 -0.074645996,
 -0.0027313232,
 0.03778076,
 0.010299683,
 -0.016204834,
 -0.017242432,
 0.027801514,
 0.02609253,
 -0.02116394,
 -0.02230835,
 -0.020828247,
 0.041046143,
 -0.01386261,
 -0.008125305,
 -0.00053215027,
 -0.0027828217,
 0.0002834797,
 0.06384277,
 -0.014129639,
 0.030258179,
 0.01259613,
 -0.04083252,
 -0.0052490234,
 -0.024551392,
 -0.014038086,
 -0.050476074,
 0.01687622,
 0.026885986,
 -0.027374268,
 0.007980347,
 0.033294678,
 0.04650879,
 0.020492554,
 0.012870789,
 -0.009216309,
 0.0069732666,
 0.0070724487,
 -0.0058784485,
 -0.030670166,
 -0.021118164,
 -0.015625,
 -0.011123657,
 -0.0027046204,
 0.03378296,
 0.023010254,
 0.03427124,
 0.0146865845,
 -0.038146973,
 0.012420654,
 -0.017425537,
 -0.012252808,
 0.0019893646,
 0.020568848,
 0.012107849,
 -0.051940918,
 -0.028747559,
 0.004753113,
 -0.017211914,
 7.402897e-05,
 -0.024032593,
 0.07312012,
 0.032287598,
 0.017166138,
 -0.011688232,
 -0.09063721,
 -0.018539429,
 0.047698975,
 -0.023147583,
 0.017349243,
 0.023239136,
 0.016494751,
 0.0262146,
 -0.06222534,
 -0.03050232,
 0.006046295,
 -0.04336548,
 5.9962273e-05,
 -0.05319214,
 0.007762909,
 -0.013641357,
 0.04586792,
 -0.05670166,
 -0.04510498,
 -0.012313843,
 0.013412476,
 -0.019683838,
 -0.0041503906,
 -0.010101318,
 -0.0040359497,
 -0.017456055,
 -0.023727417,
 0.045928955,
 -0.0033111572,
 0.0027236938,
 0.0340271,
 -0.026763916,
 -0.0030002594,
 -0.046844482,
 0.0039863586,
 -0.0009636879,
 -0.06732178,
 -0.0071792603,
 0.019195557,
 -0.025619507,
 -0.008575439,
 -0.027038574,
 0.009613037,
 -0.042999268,
 -0.026748657,
 -0.018081665,
 -0.022476196,
 -0.038848877,
 -0.03378296,
 -0.0657959,
 -0.033294678,
 -0.0054740906,
 -0.043640137,
 0.020233154,
 -0.029388428,
 -0.03152466,
 0.051971436,
 0.015342712,
 -0.013442993,
 0.008163452,
 0.030578613,
 -0.017578125,
 0.015838623,
 0.017547607,
 0.0039367676,
 -0.006816864,
 0.014060974,
 0.015701294,
 -0.031036377,
 -0.043395996,
 -0.0027332306,
 0.0029582977,
 0.040649414,
 -0.042236328,
 0.00447464,
 0.0041999817,
 0.01802063,
 -0.0007033348,
 0.004878998,
 0.01852417,
 0.00097084045,
 -0.02760315,
 0.01374054,
 -0.022644043,
 -0.02671814,
 -0.005542755,
 -0.031341553,
 -0.025970459,
 -0.025115967,
 0.014266968,
 -0.03829956,
 0.00061130524,
 0.008148193,
 0.025314331,
 -0.0058517456,
 0.005897522,
 0.024551392,
 -0.057525635,
 0.031082153,
 -0.0335083,
 0.016174316,
 -0.04525757,
 0.076416016,
 -0.060272217,
 -0.046051025,
 0.015625,
 0.025146484,
 0.03152466,
 0.03845215,
 -0.03555298,
 -0.015037537,
 0.051513672,
 0.014762878,
 0.015083313,
 0.00038790703,
 0.051239014,
 0.029815674,
 ...]

## Create Qdrant collection

In [21]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [22]:
qdrant_client.recreate_collection(
    collection_name="amazon-items-collection-00",
    vectors_config=VectorParams(size=1024, distance=Distance.COSINE),
)

C:\Users\Chanreach\AppData\Local\Temp\ipykernel_30044\3101124450.py:1: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(

True

## Embed data

Test

In [23]:
pointstruct = PointStruct(
    id=0,
    vector=get_embedding("Test text"),
    payload={
        "text": "Test text",
        "model": "embed-english-v3.0", # <-- Make sure you use the Gemini model here!
    },
)

In [24]:
pointstruct

PointStruct(id=0, vector=[-0.046691895, -0.028549194, -0.022262573, -0.012138367, -0.053253174, 0.005973816, -0.03729248, 0.035095215, 0.00072717667, 0.056549072, -0.058898926, 0.04711914, -0.0037879944, 0.030426025, -0.008743286, -0.031097412, 0.027297974, 0.003622055, -0.005569458, -0.008804321, 0.011695862, 0.024276733, -0.033325195, -0.024246216, 0.006603241, 0.036895752, 0.02720642, -0.0031814575, -0.034210205, -0.031051636, 0.013519287, 0.005214691, 0.018844604, 0.025131226, -0.009140015, 0.026016235, -0.0126571655, -0.003353119, -0.0034751892, 0.01687622, 0.01436615, 0.022659302, -0.0071144104, 0.008277893, -0.013969421, -0.06896973, 0.046142578, -0.02116394, 0.048980713, 0.0063285828, -0.0016746521, 0.041748047, -0.0044517517, -0.009796143, -0.017807007, -0.0019083023, -0.07128906, 0.049743652, 0.015594482, 0.01902771, 0.009994507, 0.036834717, 0.022323608, 0.0031471252, 0.039031982, -0.025543213, 0.036712646, 0.03062439, 0.033935547, 0.0137786865, -0.016677856, 0.0099487305, 0.02357483, -0.08935547, -0.027679443, 0.06359863, -0.042663574, -0.03074646, 0.0078086853, -0.052612305, 0.031341553, -0.019989014, 0.0009741783, 0.014320374, -0.012756348, 0.015533447, -0.0011463165, -0.005718231, -0.0209198, -0.0017719269, 0.0018119812, 0.039276123, -0.018051147, 0.0058784485, -0.018127441, -0.041931152, 0.022521973, 0.02848816, -0.010147095, 0.027359009, -0.00054073334, -0.040618896, 0.0619812, -0.044006348, 0.013977051, 0.017745972, -0.038604736, 0.0073280334, 0.03479004, 0.03704834, -0.0014209747, 0.0066108704, 0.0003516674, -0.013671875, -0.0060920715, 0.026855469, -0.0071144104, 0.016052246, -0.0041007996, 0.050872803, 0.006313324, 0.030517578, 0.017562866, -0.046173096, 0.004535675, -0.018173218, -0.0077209473, -0.03479004, 0.040252686, -0.044677734, 0.0181427, 0.052734375, -0.08581543, -0.011459351, -0.031707764, 0.03048706, -0.03466797, -0.0006351471, -0.030715942, 0.030654907, 0.019760132, -0.032958984, 0.026138306, -0.020462036, -0.021911621, 0.054016113, 0.045715332, -0.030426025, -0.02583313, -0.043121338, -0.038909912, 0.0042915344, 0.045959473, 0.010345459, -0.08557129, 0.009384155, -0.064819336, -0.0019073486, -0.025939941, -0.03677368, 0.03277588, 0.02330017, 0.0004644394, 0.014030457, -0.006855011, -0.03704834, 0.045654297, 0.026168823, 0.017959595, 0.06304932, -0.07318115, 0.03842163, 0.06750488, 0.033447266, -0.020950317, 0.0013160706, -0.008911133, 0.048339844, -0.0005106926, 0.035461426, 0.025817871, -0.056640625, -0.034942627, 0.023788452, 0.023223877, -0.07678223, 0.027832031, 0.053527832, -0.0042686462, 0.05645752, -0.03567505, -0.045013428, -0.03692627, -0.040374756, 0.032440186, 0.04055786, -0.09100342, 0.008384705, 0.0029754639, -0.015991211, 0.024673462, -0.007320404, -0.000103354454, -0.024215698, -0.03967285, -0.043914795, -0.008758545, 0.013877869, -0.018722534, -0.011978149, 0.013656616, -0.03765869, -0.0046577454, -0.0057258606, -0.017944336, -0.01927185, 0.006038666, -0.015930176, 0.007232666, -0.03656006, 0.01637268, 0.0020561218, -0.014122009, 0.02746582, -0.04046631, 0.015098572, -0.033721924, 0.048187256, 0.015625, 0.011024475, 0.10406494, -0.018508911, 0.0287323, 0.033355713, -0.0012130737, 0.014953613, 0.025558472, -0.025268555, 0.009605408, 0.013305664, 0.020111084, 0.046203613, -0.034484863, -0.041229248, 0.04309082, 0.02281189, 0.04046631, -0.05328369, 0.018554688, 0.028808594, 0.02041626, -0.008468628, 0.033966064, -0.011665344, 0.007007599, 0.030090332, -0.029586792, -0.0052337646, -0.01525116, 0.0016126633, 0.017181396, 0.02218628, -0.0010290146, 0.009513855, 0.015419006, 0.0007519722, 0.004890442, 0.008460999, -0.042388916, 0.0054359436, 0.023452759, 0.00223732, -0.044525146, -0.025405884, 0.083862305, -0.04119873, -0.07373047, 0.024032593, 0.009429932, -0.018692017, -0.033203125, -0.029022217, -0.00762558, -0.007297516, 0.041625977, 0.05130005, 0.02079773, -0.042175293, 0.009925842, 0.006187439, 0.024291992, 0.036132812, -0.011505127, 0.033569336, 0.0030841827, -0.017745972, 0.0748291, 0.018981934, 0.004070282, -0.049835205, 0.025009155, 0.014137268, -0.04736328, -0.0014324188, 0.009811401, 0.030288696, 0.015014648, -0.022857666, -0.0057258606, 0.003944397, -0.034057617, 0.002286911, -0.01411438, 0.016616821, -0.012840271, -0.024215698, 0.004699707, -0.00067949295, -0.018325806, -0.055877686, 0.085754395, 0.023208618, -0.076538086, -0.005138397, -0.03982544, 0.009788513, -0.025009155, -0.041992188, -0.078186035, -0.015541077, -0.029159546, -0.046325684, -0.02418518, 0.030059814, -0.010284424, 0.022613525, 0.029678345, -0.031188965, -0.009979248, -0.043029785, 0.010276794, 0.047576904, 0.020217896, -0.015022278, 0.0057144165, -0.043701172, -0.0067710876, -0.0060920715, -0.004573822, -0.011688232, -0.011817932, -0.037200928, 0.021697998, 0.0072746277, 0.0625, -0.028381348, -0.04473877, 0.035583496, 0.04269409, -0.03552246, -0.024887085, 0.022354126, 0.0063972473, 0.062042236, -0.04437256, -0.04031372, 0.006122589, 0.05505371, -0.0011920929, 0.03366089, 0.10046387, -0.05026245, -0.014724731, -0.022323608, -0.04135132, -0.064697266, -0.0035190582, -0.076293945, 0.050109863, -0.00036740303, -0.033203125, 0.008415222, 0.023208618, 0.04446411, -0.009048462, 0.027938843, -0.013015747, -0.0007042885, 0.033721924, 0.008773804, 0.016296387, 0.009109497, -0.040924072, -0.04095459, 0.021469116, 0.006855011, 0.013633728, 0.033691406, -0.009979248, -0.013954163, 0.037719727, 0.021575928, -0.022064209, 0.018951416, -0.022888184, -0.02243042, 0.025909424, -0.022003174, 0.033935547, 0.0256958, 0.024291992, 0.00919342, 0.019088745, -0.0009407997, -0.01902771, -0.007457733, 0.0038585663, -0.029052734, -0.001786232, 0.03326416, 0.027694702, 0.01235199, 0.0046043396, 0.042816162, 0.03161621, 0.049987793, 0.012863159, -0.0390625, 0.055480957, 0.018951416, 0.057769775, -0.020843506, -0.0005941391, 0.007419586, -0.006614685, 0.083496094, 0.00011950731, -0.000875473, 0.013282776, -0.029693604, -0.035949707, 0.012825012, 0.05343628, -0.035064697, -0.0015335083, 0.0033454895, 0.017868042, 0.021713257, -0.06750488, 0.020629883, 0.0013179779, 0.03100586, -0.024551392, 0.026535034, -0.009292603, 0.02142334, 0.024047852, 0.050079346, 0.08569336, -0.057403564, -0.027633667, -0.04562378, -0.0025196075, 0.05114746, 0.022460938, 0.017242432, 0.049316406, -0.013122559, -0.0036811829, 0.00028300285, -0.012535095, -0.04272461, 0.0006747246, -0.023483276, 0.050933838, 0.019180298, -0.038482666, -0.047790527, 0.028320312, 0.029830933, 0.013267517, 0.0026416779, 0.035614014, -0.032409668, -0.02229309, 0.02407837, -0.06933594, -0.016159058, 0.017654419, 0.04135132, 0.012763977, -0.00957489, 0.05947876, -0.009002686, -0.0071372986, 0.018447876, -0.02381897, 0.05505371, -0.012313843, -0.048583984, 0.002981186, 0.00044870377, 0.06652832, 0.018234253, 0.025482178, -0.027236938, -0.012550354, 0.013511658, 0.053985596, 0.07696533, -0.008453369, 0.03326416, -0.0044937134, 0.0054359436, -0.02571106, 0.021942139, -0.010978699, -0.029571533, 0.00053167343, 0.0036182404, 0.029663086, 0.045776367, 0.043884277, 0.02217102, -0.03302002, 0.0035133362, -0.0020751953, -0.0022335052, -0.0063285828, -0.025131226, 0.04638672, 0.037322998, -0.029953003, -0.022415161, -0.00018441677, -0.0044403076, -0.029815674, -0.0034675598, 0.0025310516, 0.01071167, -0.03567505, -0.011894226, 0.031280518, 0.040008545, 0.023864746, 0.015197754, -0.007297516, 0.03729248, -0.010643005, 0.04550171, -0.047302246, -0.048858643, -0.014755249, -0.008811951, -0.010513306, 0.014091492, -0.05206299, -0.012557983, -0.019561768, 0.061309814, 0.03866577, -0.020965576, -0.011245728, 0.004005432, -0.049804688, 0.0074768066, 0.014099121, -0.05218506, -0.0020771027, 0.0024051666, -0.008140564, -0.02130127, -0.028717041, -0.03866577, -0.013374329, -0.0023708344, 0.025802612, 0.018493652, 0.0034561157, -0.013671875, -0.00504303, 0.020324707, 0.004776001, 0.091552734, 0.008003235, 0.0791626, -0.0758667, 0.03237915, 0.011856079, 0.04071045, -0.007736206, -0.011306763, -0.0037174225, 0.0060691833, 0.019241333, -0.036712646, 0.043548584, -0.06750488, 0.00995636, -0.011871338, -0.04473877, 0.019638062, 0.003692627, -0.025604248, 0.051696777, 0.05596924, -0.013595581, 0.021881104, 0.0028362274, -0.008552551, -0.0054244995, 0.008430481, -0.037994385, 0.0046157837, -0.045532227, 0.013343811, -0.0105896, 0.048309326, 0.053955078, -0.03463745, -0.0020694733, 0.020385742, -0.0018424988, 0.04650879, -0.020950317, -0.0025310516, -0.029678345, -0.010383606, -0.007045746, -0.0044822693, -0.005039215, 0.005443573, -0.014198303, -0.029434204, -0.007457733, 0.012191772, -0.020568848, -0.046936035, -0.04815674, 0.0045776367, 0.015701294, 0.010101318, -0.031204224, -0.026290894, 0.011764526, -0.0065956116, -0.032287598, -0.019515991, -0.020996094, 0.005458832, 0.01020813, 0.014274597, -0.035064697, 0.018432617, 0.03640747, -1.8417835e-05, 0.0044136047, 0.053375244, -0.022247314, 0.0033016205, -0.04937744, -0.017150879, -0.034942627, -0.029403687, -0.038757324, 0.025100708, 0.01222229, 0.038513184, -0.03503418, 0.0019330978, 0.014549255, 0.026062012, -0.032928467, -0.027801514, -0.017532349, 0.051605225, -0.018066406, 0.03765869, -0.008659363, 0.012702942, -0.006679535, -0.048736572, 0.028335571, -0.016464233, -0.004749298, 0.041259766, -0.0143585205, -0.006931305, -0.004447937, 0.052734375, -0.02331543, 0.0041542053, 0.002231598, -0.003993988, -0.018157959, -0.04006958, -0.026290894, 0.064819336, -0.007095337, 0.0054397583, -0.0011119843, 0.0357666, -0.015899658, 0.010307312, 0.0121536255, 0.026016235, -0.0024738312, 9.357929e-06, 0.011291504, 0.001745224, 0.020339966, 0.018356323, -0.06262207, -0.040496826, 0.0077209473, -0.011978149, 0.027511597, 0.007904053, 0.00944519, 0.012908936, -0.012016296, -0.031921387, 0.029449463, -0.0018663406, 0.022109985, -0.010513306, -0.025924683, -0.0032615662, 0.012077332, 0.012191772, 0.014770508, -0.024337769, -0.009277344, -5.108118e-05, 0.012390137, -0.0015239716, -0.019592285, -0.0050201416, 0.009506226, -0.064208984, -0.05999756, -0.009819031, 0.009536743, 0.043640137, 0.031799316, 0.05041504, 0.028411865, 0.05529785, 0.012168884, 0.036010742, 0.041259766, -0.017105103, -0.03692627, 0.019851685, 0.0067100525, 0.029296875, 0.046081543, 0.014167786, -0.02368164, -0.0146865845, -0.04827881, 0.0029010773, -0.009292603, 0.026672363, 0.014640808, 0.019180298, 0.016815186, 0.01360321, -0.02645874, -0.036315918, -0.026397705, 0.002855301, -0.036254883, -0.03640747, 0.10064697, -0.019134521, -0.02267456, 0.024017334, 0.011871338, -0.0007343292, -0.028717041, 0.06756592, 0.022155762, 0.0045318604, 0.0135650635, -0.04135132, 0.0028533936, 0.0044021606, -0.007686615, 0.035003662, -0.015640259, 0.04220581, -0.009101868, 0.030700684, 0.016830444, 0.007949829, 0.015701294, 0.002817154, 0.03024292, -0.024841309, -0.039489746, -0.013656616, -0.029159546, 0.0075569153, -0.02168274, 0.013397217, 0.036224365, -0.031433105, 0.017196655, -0.021438599, 0.0072250366, 0.006095886, -0.019073486, -0.0068130493, -0.064208984, 0.042785645, 0.010055542, 0.015213013, -0.013763428, -0.06719971, 0.016601562, 0.07965088, 0.011238098, -0.019805908, -0.012626648, -0.007247925, 0.012962341, -0.009155273, 0.0027008057, -0.01285553, -0.0043754578, 0.0038719177, 0.05609131, 0.06536865, 0.06695557, -0.022460938, -0.04156494, -0.016784668, 0.008300781, 0.008544922, 0.004749298, 0.015823364, -0.03475952, -0.017822266, 0.024215698, -0.015792847, 0.0069007874, -7.402897e-05, 0.008079529, 0.07324219, 0.014198303, 0.022338867, 0.040130615, 0.0050354004, 0.0075187683, 0.03137207, 0.024154663, -0.016326904, -0.04937744, 0.020690918, 0.040924072, -0.0017375946, 0.044036865, -0.008758545, 0.028686523, 0.023468018, -0.0011177063, 0.010299683, -0.012481689, 0.0061454773, 0.0018930435, 0.028457642, 0.04510498, 0.030166626, -0.019042969, 0.024673462, 0.034454346, -0.017837524, 0.032104492, 0.020217896, -0.022949219, 0.0078125, 0.054992676, 0.016662598, 0.0052757263, -0.03050232, -0.00046420097, -0.0050239563, 0.002588272, -0.023223877, -0.032562256, -0.0016002655, -0.004749298, -0.012557983, 0.0024051666, 0.046295166, -0.024230957, 0.005054474, -0.043762207, 0.026824951, -0.020263672, -0.01876831, -0.045928955, 0.0065231323, 0.01158905, -0.03704834, -0.021209717, 0.0048217773, -0.062286377, -0.059051514, 0.0791626, -0.02381897, 0.0025939941, 0.01550293, -0.021148682, -0.023651123, -0.01928711, 0.01322937, 0.037902832, 0.016357422, -0.0058403015, 0.04083252, 0.02027893, -0.04888916, -0.06222534, -0.010017395, 0.061950684, 0.015838623, -0.04537964, 0.02218628, -0.010604858, -0.04257202, -0.013885498, -0.029067993, 0.0027770996, -0.019973755, 0.0037059784, -0.0025577545, -0.032958984, 0.022598267, -0.0011463165, -0.0027217865, 0.03366089, 0.021499634, -0.041931152, 0.084472656, -0.0048828125, 0.010185242, -0.014198303, -0.03074646, -0.020950317, -0.015701294, 0.0020313263, -0.028335571, -0.0031223297, 0.025131226, -0.07281494, -0.042907715, -0.025238037, 0.032073975, -0.013946533, -0.011924744, 0.049926758, 0.037261963, -0.049102783, -0.0018196106, -0.042297363, -0.016845703, -0.041534424, 0.027877808, 0.05596924, -0.027328491, -0.010314941, -0.031082153, -0.012382507, -0.06323242, 0.0007286072, -0.0074424744, 0.02859497, -0.041931152, 0.0006275177, 0.03829956, 0.015823364, -0.11151123, -0.085510254, 0.08465576, -0.020050049, 0.01675415, -0.021636963, 0.062438965, 0.046569824, 0.01701355, 0.0140686035, -0.009017944, -0.019454956, 0.014411926, 0.008850098, 0.017486572, -0.0047912598, -0.033935547, 0.0024261475, -0.04901123, 0.011520386, -0.074645996, -0.010719299, -0.031555176, -0.03475952, 0.028076172, -0.025741577, 0.01889038, -0.006755829, 0.014587402, -0.009124756, -0.01033783, 0.02470398, -0.028259277, -0.0027770996, -0.025161743, -0.006576538, -0.037872314, 0.002193451, 0.00082445145, -0.01739502, 0.022140503], payload={'text': 'Test text', 'model': 'embed-english-v3.0'})

## Amazon Data

In [25]:
pointstructs = []
for i, data in enumerate(data_to_embed):
    embediing = get_embedding(data["description"])
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embediing,
            payload=data,
        )
    )

In [26]:
pointstructs

[PointStruct(id=0, vector=[0.010787964, -0.026931763, -0.00573349, -0.11657715, -0.02166748, 0.035003662, -0.0791626, 0.03744507, -0.01096344, 0.013832092, -0.02557373, 0.022872925, -0.024307251, -0.011390686, 0.038024902, -0.030151367, 0.030532837, -0.019973755, 0.011116028, -0.031280518, -0.036224365, -0.0075035095, 0.019119263, -0.05718994, -0.036468506, 0.0736084, -0.03640747, -0.023071289, -0.0496521, -0.020736694, -0.008399963, 0.08496094, -0.009918213, 0.06112671, -0.06945801, -0.016326904, -0.016815186, 0.031173706, 0.0038967133, 0.01184082, -0.00289917, -0.012809753, -0.013931274, -0.047821045, -0.03930664, 0.022613525, -0.014030457, 0.003791809, 0.0036201477, -0.021209717, -0.017456055, 0.02078247, -0.025985718, 0.0126953125, 0.014282227, 0.041259766, -0.022476196, -0.03112793, -0.0053977966, 0.06573486, 0.039215088, 0.0043029785, -0.00040364265, -0.04925537, -0.007835388, -0.011138916, -0.044952393, 0.0026435852, 0.052337646, 0.027069092, -0.0061454773, -0.015670776, -0.021316528, -0.000521183, -0.038726807, 0.0011320114, 0.024627686, 0.0012674332, 0.017028809, 0.008354187, -0.07556152, -0.024810791, -0.012329102, -0.06933594, 0.017318726, -0.017227173, -0.025360107, 0.005554199, -0.019165039, 0.013328552, -0.023147583, -0.011772156, -0.007987976, 0.041992188, -0.022872925, 0.024749756, -0.010978699, 0.02520752, -0.014930725, 0.011459351, -0.01914978, -0.009117126, 0.004261017, -0.010757446, -0.012863159, 0.0065727234, 0.009338379, -0.033813477, 0.00017404556, 0.013999939, -0.026123047, 0.0035076141, 0.008163452, 0.0039863586, -0.024459839, 0.04660034, 0.0017576218, -0.00093126297, -0.008354187, 0.011192322, -0.001958847, 0.02079773, 0.01876831, 0.0035114288, 0.0206604, 0.029418945, -0.0035991669, -0.031982422, 0.028762817, -0.012512207, -0.04421997, 0.062347412, 0.014816284, -0.032928467, -0.020202637, -0.025817871, -0.004421234, 0.02331543, 0.044281006, -0.07098389, 0.06744385, 0.0009274483, 0.002073288, 0.06762695, 0.03793335, -0.017562866, 0.016296387, 0.035949707, 0.050201416, 0.0104599, 0.0025558472, 0.061340332, 0.019485474, 0.033935547, -0.03515625, -0.0039253235, -0.03149414, 0.0038318634, 0.015060425, -0.001045227, 0.014831543, 0.0058250427, 0.0011425018, 0.0107421875, 0.011680603, -0.03829956, -0.010978699, 0.006755829, 0.019165039, -0.03062439, 0.0019340515, 0.02368164, -0.0110321045, -0.0052261353, 0.010108948, 0.0053901672, -0.02067566, 0.013710022, 0.07159424, -0.109191895, -0.0791626, -0.043823242, 0.10449219, -0.03543091, -0.021453857, -0.040893555, -0.003824234, -0.009277344, 0.039489746, 0.012275696, 0.014060974, -0.0040130615, -0.022628784, -0.037261963, 0.0054092407, 0.015106201, -0.0009937286, -0.0027809143, 0.008148193, 0.013511658, 0.005340576, 0.004272461, 0.021438599, -0.02130127, -0.005607605, -0.017150879, 0.00023281574, 0.013114929, 0.0096206665, 0.03805542, -0.0026569366, 4.1127205e-06, 0.0020217896, -0.017181396, -0.01436615, 0.011306763, 0.013061523, 0.018692017, 0.041900635, -0.028030396, 0.0602417, 0.04486084, 0.037872314, 0.019729614, 0.027786255, 0.008049011, -0.015945435, 0.010688782, 0.024047852, 0.020828247, 0.011886597, 0.011131287, 0.041503906, 0.043884277, -0.04812622, -0.020767212, 0.011703491, -0.0002720356, 0.0052108765, 0.04272461, 0.024017334, -0.018615723, -0.019378662, -0.015083313, -0.027313232, -0.022827148, 0.024215698, 0.000426054, 0.013008118, 0.021255493, 0.060302734, -0.05935669, 0.019622803, -0.030090332, 0.001162529, 0.032226562, -0.023422241, 0.04586792, -0.014892578, 0.03765869, -0.07531738, -0.0055351257, 0.10913086, -0.06958008, -0.030227661, -0.0050621033, -0.009567261, 0.008880615, 0.003004074, -0.014709473, 0.020767212, -0.00076293945, 0.0039901733, 0.01247406, -0.0082473755, -0.012268066, 0.007282257, 0.012580872, -0.040893555, -0.017105103, -0.016494751, -0.014053345, -0.022705078, -0.0011043549, 0.043945312, 0.020217896, 0.010856628, 0.0045051575, 0.012023926, 0.060699463, 0.07159424, 0.0045204163, -0.011199951, 0.034729004, 0.01184845, 0.0018491745, 0.04675293, 0.036254883, -0.008598328, 0.002029419, 0.008522034, 0.03970337, -0.04800415, 0.04296875, 0.013206482, 0.027786255, 0.018539429, -0.020050049, -0.008422852, 0.015686035, -0.03842163, 0.021408081, -0.005874634, -0.0067863464, -0.035339355, -0.06121826, -0.024108887, -0.015548706, -0.072021484, -0.0058021545, 0.053527832, -0.014183044, -0.019439697, 0.031433105, -0.012069702, -0.02456665, 0.05545044, -0.024536133, -0.037139893, 0.022064209, 0.07043457, 0.042999268, 0.06781006, 0.01374054, -0.0045814514, -0.051361084, 0.00022554398, 0.032409668, 0.0058021545, 0.013031006, 0.013633728, -0.013641357, -0.008224487, -0.053527832, -0.013061523, 0.017364502, -0.031173706, 0.035888672, -0.050567627, -0.031082153, 0.01651001, -0.05545044, 0.011703491, -0.0028247833, 0.01725769, -0.0018501282, -0.036987305, 0.008621216, 0.03616333, -0.06097412, 0.023254395, 0.046783447, 0.027709961, -0.0028953552, -0.04928589, -0.06237793, 0.020523071, 0.012199402, 0.03564453, 0.0713501, -0.0105896, 0.023742676, 0.0017652512, 0.019638062, 0.0036449432, -0.0031089783, 0.026046753, -0.0368042, -0.039916992, -0.027526855, -0.03842163, -0.026504517, 0.029190063, -0.035095215, 0.0030879974, 0.03439331, -0.008003235, -0.050201416, 0.02470398, 0.0025424957, 0.0073432922, -0.009979248, 0.02949524, -0.004928589, 0.016326904, -0.004737854, -0.017242432, -0.012283325, -0.05114746, -0.01600647, -0.06964111, 0.037200928, 0.01449585, -0.021224976, -0.0011434555, -0.059753418, -0.012580872, -0.041778564, -0.0018072128, 0.064453125, -0.0035934448, -0.017684937, 0.031204224, -0.024291992, 0.001408577, 0.0051460266, -0.018600464, 0.033355713, -0.05267334, -0.020935059, -0.0054130554, 0.05343628, -0.0035324097, -0.011375427, -0.011070251, 0.04800415, -0.0060157776, 0.018463135, -0.022872925, 0.0050315857, 0.002029419, -0.014007568, -0.0023975372, -0.023849487, -0.064331055, -0.05960083, -0.014442444, 0.014015198, 0.03286743, -0.039489746, 0.035888672, 0.023254395, -0.014549255, -0.018371582, -0.0021591187, -0.026626587, 0.05996704, 0.024658203, -0.05987549, 0.0057754517, -0.06878662, 0.027954102, -0.041290283, 0.047454834, -0.0069885254, -0.018615723, 0.002626419, 0.029968262, -0.016204834, 0.008018494, -0.0032539368, -0.016815186, 0.008972168, -0.030532837, -0.031799316, 0.0055503845, 0.030334473, 0.0066986084, -0.025894165, -0.016235352, -0.025939941, 0.028640747, 0.027664185, -0.009490967, 0.027618408, -0.00806427, -0.01171875, 0.044799805, -0.070373535, -0.025421143, -0.020141602, -0.008598328, 0.012619019, 0.05279541, 0.0124053955, -0.00063705444, 0.035888672, 0.06427002, 0.012710571, -0.017822266, -0.08843994, 0.007511139, 0.008987427, -0.028198242, -0.003929138, 0.040924072, 0.0032730103, -0.026519775, 0.040802002, -0.031433105, -0.030822754, -0.0039138794, -0.011421204, -0.038360596, 0.008140564, 0.0054473877, -0.017593384, 0.0026550293, 0.008995056, -0.010047913, 0.010505676, -0.03729248, 0.0107421875, -0.02279663, -0.010627747, 0.012008667, -0.014823914, -0.0115356445, -0.03237915, 0.0036010742, 0.0018196106, 0.0021381378, 0.0284729, 0.003528595, 0.010391235, -0.021636963, 0.056671143, 0.025253296, -0.030929565, -0.002231598, 0.008460999, 0.0062446594, -0.005420685, -0.0098724365, 0.030319214, 0.0027275085, -0.0068740845, -0.012649536, -0.012802124, -0.0519104, 0.0118637085, 0.008377075, -0.026123047, -0.031707764, -0.011184692, -0.008331299, -0.024749756, 0.025390625, -0.045043945, 0.029037476, -0.010375977, -0.03781128, 0.025848389, -0.009483337, -0.035003662, -0.0040779114, -0.015838623, 0.0070266724, 0.012573242, 0.019699097, 0.021942139, 0.06149292, -0.024978638, -0.07574463, 0.0077781677, 0.012237549, 0.020233154, -0.01184845, 0.04373169, -0.056243896, -0.027359009, -0.059295654, -0.0446167, -0.024673462, 0.0038146973, 0.035461426, -0.0004401207, 0.020858765, -0.018112183, 0.05407715, -0.0134887695, 0.07849121, 0.009811401, 0.11206055, -0.04815674, -0.016448975, 0.03439331, -0.040924072, -0.053894043, -0.04522705, 0.039794922, 0.0047721863, -0.0015087128, -0.058654785, 0.01398468, -0.017547607, 0.007850647, 0.0037155151, 0.009475708, 0.013153076, 0.0040512085, 0.008842468, -0.0090408325, -0.006893158, -0.039123535, 0.029449463, 0.028305054, -0.016082764, -0.03466797, -0.028182983, 0.007911682, -0.0012741089, -0.0044059753, -0.0015325546, -0.014526367, 0.02168274, -0.03427124, 0.055511475, 0.0070381165, 0.0037956238, 0.012390137, -0.009498596, -0.017852783, -0.042388916, -0.020584106, 0.024551392, 0.034240723, -0.04156494, -0.062927246, 0.02279663, -0.09136963, 0.007457733, -0.052246094, -0.018447876, -0.015365601, 0.027450562, -0.0051651, -0.025283813, 0.019577026, -0.04168701, -0.022537231, 0.01159668, 0.038116455, 0.024398804, -0.043640137, -0.05847168, 0.0009737015, -0.015312195, -0.0031909943, 0.03137207, 0.010803223, 0.020874023, -0.031921387, -0.030075073, 0.082092285, -0.030975342, 0.012748718, 0.019256592, -0.01789856, -0.046936035, -0.020339966, -0.018585205, -0.0010547638, -0.05480957, -0.007270813, -0.024414062, -0.0087890625, 0.03881836, -0.049865723, 0.013916016, -0.005683899, -0.0064468384, 0.018875122, -0.043060303, 0.023040771, -0.051208496, -0.015602112, 0.007171631, -0.011314392, -0.052703857, 0.008491516, -0.013832092, 0.021575928, -0.03286743, -0.013847351, 0.024932861, -0.07159424, 0.0059013367, 0.028259277, -0.008766174, -0.06555176, -0.00048398972, 0.016860962, -0.0039787292, -0.029464722, 0.049713135, -0.033447266, 0.030456543, 0.0029182434, 0.05822754, 0.035247803, -0.017410278, -0.013557434, -0.027160645, 0.028198242, -0.005947113, -0.009780884, -0.026168823, 0.009849548, 0.011260986, -0.009292603, 0.024307251, -0.05529785, -0.025848389, -0.025222778, 0.012542725, 0.045074463, 0.044677734, 0.03869629, 0.0011911392, -0.015533447, -0.028427124, -0.0025100708, -0.05255127, -0.012283325, 0.0104522705, -0.014549255, 0.025283813, -0.0115737915, -0.01777649, -0.014968872, 0.0121536255, 0.04019165, -0.044769287, -0.028289795, -0.025894165, 0.08526611, -0.046173096, -0.034088135, 0.019729614, -0.007133484, 0.02116394, 0.015838623, -0.047058105, 0.03366089, 0.030593872, 0.010398865, 0.041748047, -0.021835327, 0.018432617, -0.00365448, -0.018417358, -0.03704834, -0.003419876, -0.007347107, -0.009239197, 0.047790527, 0.02456665, -0.041046143, -0.014289856, -0.009742737, 0.016571045, -0.006046295, -0.012512207, -0.019241333, 0.009178162, 0.0072669983, 0.02796936, 0.04260254, 0.02709961, 0.007873535, 0.033843994, 0.025344849, 0.04034424, -0.076049805, 0.037139893, 0.00806427, -0.052581787, 0.03439331, 0.012718201, 0.0040130615, 0.015899658, 0.0011644363, -0.008834839, -0.039855957, 0.027328491, 0.034118652, 0.058929443, -0.049102783, -0.0067977905, 0.033843994, 0.05758667, 0.02407837, -0.03729248, 0.008361816, 0.027038574, -0.010643005, -0.0071907043, -0.0107803345, -0.017425537, -0.016967773, -0.0042304993, -0.020050049, -0.0076446533, -0.018493652, -0.004184723, 0.044189453, -0.016403198, 0.015380859, -0.013397217, 0.016693115, -0.037261963, -0.015319824, 0.040649414, -0.0076065063, 0.036376953, -0.06781006, 0.009254456, -0.051940918, -0.024658203, 0.024673462, 0.04260254, -0.008171082, 0.016296387, -0.0018596649, 0.0013132095, 0.03363037, -0.009788513, 0.020355225, 0.056671143, 0.038482666, 0.01109314, -0.00032901764, 0.043029785, 0.039001465, 0.017684937, -0.04348755, 0.020645142, -0.00017726421, -0.007549286, -0.0047073364, 0.031036377, -0.028305054, -0.019470215, 0.037139893, 0.010528564, 0.013725281, -0.01473999, -0.016235352, -0.006942749, 0.06149292, 0.017959595, -0.029846191, 0.021255493, 0.019332886, -0.01309967, 0.008125305, -0.04083252, -0.015472412, 0.0022850037, 0.00919342, -0.00086069107, -0.04095459, -0.041900635, 0.019500732, 0.012779236, -0.0032482147, -0.020996094, 0.010902405, -0.015586853, 0.023620605, 0.024459839, -0.003967285, -0.03878784, -0.016098022, -0.02407837, 0.022842407, -0.03265381, 0.014633179, 0.012245178, -0.0038108826, 0.016921997, -0.006919861, -0.1038208, 0.0045166016, 0.06036377, 0.0065460205, 0.029190063, -0.033081055, -0.008811951, -0.0004734993, -0.028747559, 0.045043945, -0.0027484894, -0.025878906, -0.04510498, -0.0058631897, 0.007797241, -0.01991272, -0.053131104, 0.012130737, -0.006801605, 0.052825928, -0.057006836, 0.04525757, -0.047027588, -0.06970215, -0.036132812, -0.066711426, -0.050445557, 0.11029053, -0.009140015, -0.004699707, 0.010757446, -0.03552246, 0.010177612, -0.0036201477, 0.021972656, 0.05670166, 0.016967773, -0.008110046, 0.0647583, -0.0067749023, -0.025924683, -0.08178711, -0.012252808, -0.051605225, 0.036010742, 0.0045433044, 0.004463196, 0.014808655, -0.010368347, 0.02407837, 0.005302429, 0.015304565, -0.014533997, 0.0008955002, -0.04083252, -0.033477783, 0.03111267, 0.014289856, -0.03778076, 0.0018138885, 0.04598999, -0.032409668, 0.035339355, -0.035247803, 0.009254456, -0.083618164, -0.009269714, -0.016113281, -0.021774292, -0.0036296844, -0.0021572113, 0.004737854, 0.02696228, -0.034698486, -0.035736084, -0.009925842, 0.00554657, 0.0031414032, 0.07714844, -0.03149414, -0.0071868896, -0.025054932, 0.0982666, -0.010528564, -0.006198883, -0.008644104, -0.01777649, -0.006023407, 0.03579712, -0.023788452, 0.051696777, 0.059448242, -0.013572693, 0.030731201, 0.007457733, -0.02532959, 0.013839722, -0.0077285767, 0.08325195, 0.03805542, -0.009239197, -0.011871338, 0.01914978, 0.00881958, 0.02053833, -0.018875122, 0.015144348, -0.00094270706, 0.012390137, -0.0335083, -0.033935547, -0.007118225, 0.015686035, -0.029632568, -0.010826111, 0.008621216, 0.009841919, 0.0018835068, -0.0009784698, 0.012054443, -0.0015687943, -0.012023926, 0.022705078, 0.013000488, 0.023666382, -0.05999756, 0.006587982, -0.044769287, 0.014373779, 0.020446777, 0.008155823, 0.07501221, -0.03012085, -0.0079193115, -0.034942627, -0.0020713806, -0.041015625, 0.013343811, 0.02128601, -0.009552002, 0.032958984], payload={'description': "BoYata Screen Cleaner Kit 4PCS, 3-in-1 Touchscreen Mist Cleaner Spray Bottle Tool & Microfiber Cloth, Portable Reusable Fingerprint-Proof Spray Bottle for Phone/Laptop/Tablet/TV/Monitor/Car Screens Not Containing Cleaning Fluid: BoYata all-in-one detachable fingerprint-proof computer screen cleaner consists of a protective case, microfiber cloth shell and spray bottle (without cleaning fluid), integrated spray and wipe in one. Extremely convenient to use after filling cleaning fluid. Note: please don't put corrosive liquids. Wide Compatibility: The touch screen mist cleaner is useful for screen cleaning. Suitable for all phones/ tablets/ laptops/ monitors/ TVs/ cars screens, glass surface etc. Spray and wipe in one for quick and easy cleaning, making your screen look as good as new. Safe and no damage to your screen. Powerful Cleaning: The updated microfiber cloth of the screen cleaner is easy to move fingerprints, dust, grease, dirt on screen without streaking or scratching. Well absorbent and no shedding hair. Unlike other products, it has a silicone scraper on the back that effectively removes stubborn stains on the screen. Washable & Reusable: The gentle microfiber cloth with a hot pressing technique, not degumming and the laptop screen cleaner is washable that the cleaner surface is dirty, can be washed directly with clean water and then reuse after drying. The 10,5 ml spray bottle can easily be refilled to use again. Lightweight & Portable: The phone screen cleaner is very lightweight in size and weight, a size of a lipstick, fits easily into a pocket, handbag, makeup bag, backpack or car, etc, easy to carry. The ABS transparent protective case effectively protects your bag or pocket from getting dirty. Kindly contact us if there is any product issue.", 'image': 'https://m.media-amazon.com/images/I/41x2+vIHjNL._AC_.jpg', 'rating_number': 105, 'price': 11.99, 'average_rating': 4.6, 'parent_asin': 'B0C3VNSX6X'}),

In [27]:
len(pointstructs)

50

## Write embedded data to Qdrant database

In [28]:
qdrant_client.upsert(
    collection_name="amazon-items-collection-00",
    wait=True,
    points=pointstructs,
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

## Define a fucntion for data retrieval

In [29]:
def retrieve_data(query, k=5):
    query_embedding = get_embedding(query)
    results = qdrant_client.query_points(
        collection_name="amazon-items-collection-00",
        query=query_embedding,
        limit=k,
    )
    return results

### Test Retrieval

In [30]:
retrieve_data("what kind of products that are available?", k=10).points

[ScoredPoint(id=48, version=1, score=0.326369, payload={'description': "Parblo PR114 Drawing Tablet Stand Holder Adjustable,Sturdy Portable Monitor Stand Desktop Stand Compatible with ipad/air/Mini/pro,Kindle,Surface,Samsung Tab,Phone Foldable & Wide Compatibility: With Foldable design,weight is only 200g,Our tablet holder is convenient to storage and transportation.Convenient to use at home or in conference rooms, anywhere outdoors.The Tablet stand for desk can fit for up to 11inch tablet,Compatible for iPad mini /air/pro series,Samsung Galaxy Series,Huawei MatePad Series, Lenovo Tab P11 Pro,Microsoft Surface,All Phones. Exquisite structure & weight resistance 10kg: From the aluminum alloy material to the overall structure, the tablet holder details are carefully crafted. Unique double triangular structure, no tilt, can be used stably outdoors, and can withstand 10 kg. Adjustable angle & improve posture: The ipad holder stand is Based on ergonomics, it can adjust the most suitable angle for oneself during work, improve sight, improve posture, correct, reduce the burden on shoulders and neck when working a long time, effectively prevent hunchback Superior heat dissipation effect & with protective pad: The aluminum alloy bracket that is easy to cool is set up, the heat is not easy to be tired, and the natural heat dissipation of notebook computers and other equipment is realized. Quality Guarantee: 12 months warranty period from the date of placing the order. Before shipping the portable monitor stand, we carry out strict inspection procedures. If there is a problem or something you don't understand, please contact us by email. We will reply you within 24 hours.", 'image': 'https://m.media-amazon.com/images/I/4125HxmnX+L._AC_.jpg', 'rating_number': 702, 'price': 23.99, 'average_rating': 4.6, 'parent_asin': 'B09LM58PMM'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=14, version=1, score=0.3216892, payload={'description': "Ring Light for Computer, Video Conference Lighting, Laptop Light with Clamp for Video Calls, Zoom Meetings, Online Teaching, Webcam Lighting, Live Streaming, Self Broadcasting, Virtual Chat Professional Video Conference Light - Our portable mini ring lights built in 60 LED light beads provide warm light that smooths out the shadows to highlight your face rather than the background. Upgrade thickened lampshade make the light soft and not dazzling, the eyes will not be tired after long-time use. Upgraded Screen Protective Clamp - Our webcam light features a stable clamp that can be easily clipped on. The soft rubber pad will securely onto your device and protect your device's surface well. Open mouth up to 0.9 inches. 3 Lighting Modes and 10 Level Brightness - Our laptop light comes with an integrated controller that allows you to choose preferred lighting mode (white light/nature light/warm light) and it has 10 level brightness for each lighting modes so you can match it to your surroundings or combine it with the existing lights in your room. Multiple Way To Use - Auxiwa 6.3-inch small selfie light comes with a clamp to attach to a laptop and desktop monitor. Its unique design also allows it to stand on the desktop alone. It's really a great webcam light for anyone using Zoom or Skype video calls. Multifunctional Lighting - If you need a soft LED circle light for your online class or videos calls, Axuiwa computer ring light is your must-have. It's perfect for video conferencing, zoom meeting, video calls, remote online working, live streaming", 'image': 'https://m.media-amazon.com/images/I/41PAR99b8EL._AC_.jpg', 'rating_number': 143, 'price': 7.99, 'average_rating': 4.3, 'parent_asin': 'B0B3F23L11'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=13, version=1, score=0.31920657, payload={'description': 'MEEgoodo for MacBook Pro Case 13 inch 2022 2021 2020 A2338 M2/M1 A2251 A2289 with Touch ID, Clear Laptop Hard Shell with Keyboard Webcam Cover & Trackpad Film & Type C Adapter, Abstract Floral & Leaf 𝘾𝘼𝙎𝙀 𝙁𝙊𝙍 𝙈𝘼𝘾𝘽𝙊𝙊𝙆 𝙋𝙍𝙊 𝟭𝟯 𝙒𝙄𝙏𝙃 𝙈𝟮 𝘾𝙃𝙄𝙋 𝟮𝟬𝟮𝟮 𝟮𝟬𝟮𝟭 𝟮𝟬𝟮𝟬 - Designed for MacBook Pro 13 Case 2022 2020 2021 Released(Compatible Model: A2338 M2 M1 A2251 A2289 with Touch ID & Retina Display) [NOT compatible with Macbook Pro 13 2019 2018 2017 2016 with Touch Bar and Retina Display Model: A2159/A1989/A1706/A1708 and Old Pro 13 inch with Retina Display Release before 2016 A1502/A1425. Please kindly check your Macbook model "AXXXX" on the back before purchase. 𝙈𝙐𝙇𝙏𝙄𝙁𝙐𝙉𝘾𝙏𝙄𝙊𝙉 - Macbook pro 2020 case with glossy clear top cover and bottom shell lightweight to resist scratches and skidding, impact protection. Precise construction allows complete access to all ports, features, buttons and Touch ID function. Simple clip-on/off design without the added risk of harming your laptop during application. Anti-slip with black rubber four stands at the bottom. 𝗔𝗗𝗔𝗣𝗧𝗘𝗥 𝗙𝗨𝗡𝗖𝗧𝗜𝗢𝗡 - MEEgoodo provides silver adapter for you. The adapter USB Type-C end into laptop USB-C port, then connect another female USB 3.0 port to standard USB-A device, such as, mouse, keyboard, SSD and flash. Support OTG function to load USB flash disk directly. This USB Type-C to USB connector also support synchronous charging to your phone and tablet with data transfer. This USB-C to USB 3.0 converter is made of zinc alloy with baking finished surface. 𝙋𝘼𝘾𝙆𝘼𝙂𝙀 𝙄𝙉𝘾𝙇𝙐𝘿𝙀𝘿 - Including 1 PC Hard Shell Case with Painting, 1 matching Keyboard Cover, 1 Trackpad Protector & 1 Type C Adapter, 2 Webcam Covers.The matching keyboard cover provides full protection for your MacBook keyboard against key wear.Trackpad Protector Cover made from triple layer high quality electrostatic material to protect the MacBook trackpad area from scratches and daily wear and tear. And webcam cover guarding your personal privacy. 𝘾𝙐𝙎𝙏𝙊𝙈𝙀𝙍 𝙎𝙀𝙍𝙑𝙄𝘾𝙀 - If you are not satisfied with the performance of MEEgoodo\'s case for MacBook Pro 13 inch, please contact us and we will give you a refund.', 'image': 'https://m.media-amazon.com/images/I/51tfeLxoZ6L._AC_.jpg', 'rating_number': 108, 'price': 23.99, 'average_rating': 4.0, 'parent_asin': 'B099F1BH44'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=31, version=1, score=0.3156842, payload={'description': 'FONVOi 2 Pack AUX Cable(4FT,1.2M), Braided 3.5mm Audio AUX Cord for Car,3.5mm Male to Male Stereo Cable, Compatible with:Headphones, Phones, iPod,Car Audio,MP3 and More 【Plug and Play】FONVOi 3.5mm male-to-male audio cable can directly connect devices with 3.5mm jacks to transmit Hi-Fi stereo audio without any driver or adapter, allowing you to enjoy music anytime, anywhere. 【Durability】The FONVOi 3.5mm aux cable is made of nylon braid to protect and strengthen the wire splice to withstand the twisting, dragging and tangling of over 1000 bend tests. 【Universal Compatibility】This 3.5mm audio cable is perfectly compatible with devices with 3.5mm auxiliary interface: ipod/headphone/Hi-Fi/car music/tablet/computer notebook/smartphone/MP3/player/speaker and any other Audio playback device with 3.5mm aux. 【Superior Sound Quality】The 3.5mm audio cable features 24 gold-plated corrosion-resistant connectors and double shielding to ensure reliability and eliminate possible signal loss and noise, bringing lossless, noise-free, high-fidelity audio experience to your devices. 【WHAT YOU WILL GET】 FONVOi We offer 2 packs of 4ft 3.5mm Audio Cables with a two year worry free warranty, if you have any questions, please contact our customer support team and we will respond by email within 24 hours.', 'image': 'https://m.media-amazon.com/images/I/41mwe+IWO+L.jpg', 'rating_number': 213, 'price': 5.99, 'average_rating': 4.5, 'parent_asin': 'B0C3HC6S6R'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=16, version=1, score=0.30265683, payload={'description': "OKP Case for iPad 6th Generation/iPad 5th Generation/iPad 9.7 inch/\xa0iPad Air 2, Hybrid Shockproof Rugged Protective Cover for ipad 9.7 inch 2018/2017 with Built-in Kickstand (Alpine Green+Black) 【Compatible Models】 OKP case compatible with iPad 9.7 inch ipad 6th generation 2018 model & ipad 5th generation 2017 model & ipad Air 2 (2014 model) &. Model Number: (A1893/A1954/A1822/A1823/A1566/A1567). NOT fits for any other devices. 【Shockproof Rugged Design】 This case for iPad 6th generation kids made of durable hard PC+silicone, 3-layer full body protection structure, provide a perfect protection & anti-scratch. NOTE: This ipad 9.7 inch case WITHOUT built-in screen protector. 【Functional Kickstand】 Case for ipad air 2 built-in convenient kickstand with 2 angles: Typing & Viewing angles. Convenient for studying, gaming, watching video, etc. 【Precise Cutouts】 The case for ipad 5th generation kids is easy to access all buttons, speakers, cameras through the precisely-cut openings. Especially the charging port with rubber flap which can keep dust out. It's also a nice and practical gift for your kids and friends. 【What You Get】 If you have any questions of our case for ipad 6th/5h generation & ipad air 2, please feel free to contact us at any time. We sure all the question can be solved properly.", 'image': 'https://m.media-amazon.com/images/I/41IsRnlGrqL._AC_.jpg', 'rating_number': 1788, 'price': 21.99, 'average_rating': 4.5, 'parent_asin': 'B09N8YHRTF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=9, version=1, score=0.30241528, payload={'description': 'Laptop Camera Cover Slide, [8 Pack]Ultra-Thin Webcam Cover Compatible with MacBook,Laptop,PC,Computer,iMac,iPad, iPhone Cell Phone etc. 0.022in Thick Web Blocker Protect Your Privacy and Security ★【Protect Privacy Security】Focusing on network security, now we can easily and effectively protect personal and family privacy security , Just gently slide the slide and close the camera, you can stop the intrusion of hackers. ★【 Ultra Thin And Durable】The new ultra-thin design, with a thickness of only 0.022 inches, is made of flexible ABS material and is not fragile. Will not affect the closing of the laptops and scratch the laptops. ★【Easy to install】 Strong adhesive makes the cover not fall, keep the screen clean and free of stains during installation, tear off the adhesive tape on the back, align it with our camera, and press hard for 10 seconds to work. ★【Compatible with 】Compatible for Laptop,Apple MacBook Pro,Macbook Air,iMac ,Mac mini,iPad, tablet, computers, MacBook Air, iPhone,Cell Phone etc front camera Echo Show and desktops.', 'image': 'https://m.media-amazon.com/images/I/315jMKv-yhL._AC_.jpg', 'rating_number': 9329, 'price': 6.91, 'average_rating': 4.3, 'parent_asin': 'B095NVKM7V'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=24, version=1, score=0.2935338, payload={'description': "Gueray CD Player Portable Bluetooth Desktop CD Player for Home with Timer Built-in HiFi Speakers with LCD Screen Display Boombox FM Radio USB Type-c Multi-functional CD Player: 1.Desktop CD Player, 2.Bluetooth 5.0 HiFi Speaker, 3. FM Radio, 4.USB Flash Drive Player, 5. 3.5mm Audio Player. Support CD, CD-G, MP3, WMA. 6 in 1 CD Player makes your life more colorful and bringing unforgettable memories. Buy One Get Four Free: Desktop CD Player, Remote Control, USB-Type-c Adapter and 3.5mm Audio Cable Bluetooth CD Player: Apply Bluetooth 5.0 technology on this portable wall CD player, which features wider signal range, faster connection and transmission speed. Built-in dual Hi-Fi Bluetooth speakers, which can be connected with Bluetooth-enabled devices such as mobile phone or tablet. It will work as a wired speaker. NOTICE: It's a Bluetooth transmitter and receiver Desktop Design: Desktop design with update also can as a Bluetooth transmitter, one plays all multiple functions of remote control. Easy to stand on the desk without Assembly or other support. Making your home more elegant and artistic (NOTICE: This CD player have a front cover) Wired Speaker: Connect the CD player to other external wired devices such as mobile, tablet or laptop via 3.5mm male-to-male audio cable, it will work as a wired speaker. Using this audio cable you can also connect and output the CD player to other external wired speakers (Notice: Remote control does not included batteries) Great Gift: This Gueray CD Player is a perfect gifts for kids, elders, parents, friends and pregnant women etc. The CD player supports remote control within 5 meters, A-B repeat, suitable for language learning, prenatal education / antenatal training, early education, FM radio broadcast, CD/USB/MP3 music player and home or coffee house decoration", 'image': 'https://m.media-amazon.com/images/I/51dyqsm5JxL._AC_.jpg', 'rating_number': 395, 'price': 49.98, 'average_rating': 4.4, 'parent_asin': 'B0BZL6B7GB'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=0, version=1, score=0.28891551, payload={'description': "BoYata Screen Cleaner Kit 4PCS, 3-in-1 Touchscreen Mist Cleaner Spray Bottle Tool & Microfiber Cloth, Portable Reusable Fingerprint-Proof Spray Bottle for Phone/Laptop/Tablet/TV/Monitor/Car Screens Not Containing Cleaning Fluid: BoYata all-in-one detachable fingerprint-proof computer screen cleaner consists of a protective case, microfiber cloth shell and spray bottle (without cleaning fluid), integrated spray and wipe in one. Extremely convenient to use after filling cleaning fluid. Note: please don't put corrosive liquids. Wide Compatibility: The touch screen mist cleaner is useful for screen cleaning. Suitable for all phones/ tablets/ laptops/ monitors/ TVs/ cars screens, glass surface etc. Spray and wipe in one for quick and easy cleaning, making your screen look as good as new. Safe and no damage to your screen. Powerful Cleaning: The updated microfiber cloth of the screen cleaner is easy to move fingerprints, dust, grease, dirt on screen without streaking or scratching. Well absorbent and no shedding hair. Unlike other products, it has a silicone scraper on the back that effectively removes stubborn stains on the screen. Washable & Reusable: The gentle microfiber cloth with a hot pressing technique, not degumming and the laptop screen cleaner is washable that the cleaner surface is dirty, can be washed directly with clean water and then reuse after drying. The 10,5 ml spray bottle can easily be refilled to use again. Lightweight & Portable: The phone screen cleaner is very lightweight in size and weight, a size of a lipstick, fits easily into a pocket, handbag, makeup bag, backpack or car, etc, easy to carry. The ABS transparent protective case effectively protects your bag or pocket from getting dirty. Kindly contact us if there is any product issue.", 'image': 'https://m.media-amazon.com/images/I/41x2+vIHjNL._AC_.jpg', 'rating_number': 105, 'price': 11.99, 'average_rating': 4.6, 'parent_asin': 'B0C3VNSX6X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=47, version=1, score=0.2885755, payload={'description': "SoundPEATS Air Conduction Headphones, RunFree Lite Open-Ear Sports Bluetooth V5.3 Headphones with Bass Boost and 17 Hours, Sweatproof Ultralight Headset for Running, Workouts, Comfortable Fit, USB-C 𝗨𝗻𝗯𝗲𝗮𝘁𝗮𝗯𝗹𝗲 𝗖𝗼𝗺𝗳𝗼𝗿𝘁 𝗮𝗻𝗱 𝗟𝗶𝗴𝗵𝘁𝘄𝗲𝗶𝗴𝗵𝘁 𝗗𝗲𝘀𝗶𝗴𝗻 - 🍀 𝘽𝙚𝙨𝙩 𝙑𝙖𝙡𝙪𝙚 𝙊𝙥𝙚𝙣-𝙚𝙖𝙧 𝙎𝙥𝙤𝙧𝙩 𝙃𝙚𝙖𝙙𝙥𝙝𝙤𝙣𝙚 - 𝘾𝙉𝙀𝙏 🍀. The RunFree Lite headset is carefully optimized for weight distribution, ensuring a secure and comfortable fit that eliminates worries of slipping and shaking. Wrapped in skin-friendly liquid silicone, these lightweight headphones (0.99oz) provide a weightless and comfortable experience for extended listening during gym sessions, exercise, running, and more. 𝗢𝗽𝗲𝗻-𝗘𝗮𝗿 𝗗𝗲𝘀𝗶𝗴𝗻 𝗮𝗻𝗱 𝗗𝘆𝗻𝗮𝗺𝗶𝗰 𝗦𝗼𝘂𝗻𝗱 - Stay connected and aware of your surroundings with our open-ear design sports headphones, which use air conduction technology to enhance the aerodynamic transmission of sound, resulting in a more dynamic and powerful audio experience. Enjoy up to 17 hours of playtime on a single charge to keep your music going for daily and weekly exercises. Only 1-2 hours charge will get full energy back. 𝗣𝗼𝘄𝗲𝗿𝗳𝘂𝗹 𝗕𝗮𝘀𝘀 𝗮𝗻𝗱 𝗦𝘁𝗮𝗯𝗹𝗲 𝗖𝗼𝗻𝗻𝗲𝗰𝘁𝗶𝗼𝗻 - Featuring the latest low-frequency enhancement technology and Bluetooth 5.3 transmission, our headphones offer a seamless audio experience with a significant reduction in distortion and enhanced sound quality. The built-in 16.2mm drivers with an open soundstage improve the sound further, delivering even more powerful bass for a truly immersive audio experience. 𝗖𝗿𝘆𝘀𝘁𝗮𝗹-𝗖𝗹𝗲𝗮𝗿 𝗖𝗮𝗹𝗹𝘀 𝗮𝗻𝗱 𝗗𝗶𝗿𝗲𝗰𝘁𝗶𝗼𝗻𝗮𝗹 𝗦𝗼𝘂𝗻𝗱 - Experience crystal-clear audio with our directional sound transmission technology that significantly reduces sound leakage. Equipped with a dual-beamforming microphone array featuring a noise reduction optimization algorithm, which isolates and enhances your voice while filtering out background noise, making phone calls and video conferences feel like face-to-face conversations. 𝗦𝘄𝗲𝗮𝘁𝗽𝗿𝗼𝗼𝗳 𝗮𝗻𝗱 𝗠𝘂𝗹𝘁𝗶𝗽𝗼𝗶𝗻𝘁 𝗖𝗼𝗻𝗻𝗲𝗰𝘁𝗶𝗼𝗻 - The RunFree Lite headset is IPX4-rated and equipped with an anti-sweat design, making it perfect for carefree exercise and outdoor activities in all weather conditions. It can also pair with two devices simultaneously, allowing for seamless multitasking. For more personalized features, download and register the SoundPEATS App. (📱: The App supports upgrading the firmware. 🎯 Note: Please rest assured, the headphone works very well if you don't want to download and register the App.)", 'image': 'https://m.media-amazon.com/images/I/31OGeYLIfnL._AC_.jpg', 'rating_number': 132, 'price': 29.99, 'average_rating': 4.0, 'parent_asin': 'B0BRXDR9GF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=27, version=1, score=0.28773004, payload={'description': 'USB C to 3.5mm Headphone and Charger Adapter, 2 in 1 USB C to 3.5mm Audio and PD 60W Fast Charge Fit for Galaxy S23 S22 S21 S20 Ultra Note 20 10, Google Pixel 7 6 Rro 5 4 XL 3 XL 2XL,iPad Pro (Grey) 【MIni 2 in 1 Adapter】 With the usb c headphone and charger adapter, you can listen to music and charge your phone at the same time. This convenient usb type-c to 3.5mm adapter supports music playback and calling for most USB C devices. Plug and play, no driver installation required.NOTE:Dose not support data transfer 【HIFI audio playing】 Support hi-fi sound up to 24 bit / 384 kHz, while others are 16 bit / 48 kHz. Built-in a high-quality DAC chip ensures stable and lossless audio signal transmission, no current noise. The usb c to aux adapter compatible with CTIA and OMTP. 【Supports PD 60W Fast Charging】 Support PD 3.0 fast charging protocol, up to 20V/3A charging. Built-in a powerful EJ899M Chip identifies the voltage and current required by different electronic products and satisfies the different needs, ensures the stability of charging voltage and current to protect your devices. NOTE: Suggest using PD wall charger to get faster charging speed. WIDELY COMATIBILITY: Our c to aux adapter is perfect for the new released Samsung Galaxy S22/S22+/S22 Ultra. And fit for Samsung S21 S20 S20 +/Note 20 20Ultra 5G/Note 10, Google Pixel 3/4/5/6/6pro XL, MacBook Pro 2020/iMac, Huawei Mate 20 Pro/Mate 30 Pro/Huawei P30 Pro/P40 Pro and more. Support phone calling and music control for most USB-Type C enabled devices in the market. 【Mini Design & 18 Month Warranty】This is the most Mini design on the market,We provide this USB C to 3.5mm Female Adapter with 18 month Warranty, If you have any questions about this Type c to 3.5mm Aux Adapter,we are happy to assist until your problem solved.', 'image': 'https://m.media-amazon.com/images/I/31JYd-quF8L._AC_.jpg', 'rating_number': 110, 'price': 11.99, 'average_rating': 3.8, 'parent_asin': 'B0BYCMG5BC'}, vector=None, shard_key=None, order_value=None)]